// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Integration tests for `ty trace mine` (spec mining v1).
//!
//! The closed loop under test: `ty trace-gen` produces traces from a known
//! small spec, `ty trace mine` synthesizes a candidate spec from them, and
//! the mined spec must (a) model check clean, (b) validate the generating
//! traces, and (c) recover the expected domain/monotonicity/update-pattern
//! candidates.

use std::path::Path;
use std::time::Duration;

mod common;
use common::TempDir;

fn run_tla(args: &[&str]) -> (i32, String, String) {
    common::run_tla_parsed_with_timeout(args, Duration::from_secs(60))
}

fn assert_ok(code: i32, stdout: &str, stderr: &str) {
    assert_eq!(
        code, 0,
        "expected exit 0\nstderr:\n{stderr}\nstdout:\n{stdout}"
    );
}

fn assert_contains(haystack: &str, needles: &[&str]) {
    for needle in needles {
        assert!(
            haystack.contains(needle),
            "missing {needle:?} in:\n{haystack}"
        );
    }
}

/// A bounded counter: deadlocks (terminates) at x = 5.
fn write_counter_spec(dir: &Path) -> (std::path::PathBuf, std::path::PathBuf) {
    let spec_path = dir.join("Counter.tla");
    let cfg_path = dir.join("Counter.cfg");
    common::write_file(
        &spec_path,
        br#"---- MODULE Counter ----
EXTENDS Integers
VARIABLE x
Init == x = 0
Inc == x < 5 /\ x' = x + 1
Next == Inc
====
"#,
    );
    common::write_file(&cfg_path, b"INIT Init\nNEXT Next\n");
    (spec_path, cfg_path)
}

/// Mining traces generated by `ty trace-gen` from the counter spec recovers
/// the expected candidates, checks clean, and validates the corpus.
#[cfg_attr(test, ntest::timeout(120000))]
#[test]
fn mine_from_trace_gen_counter_closes_the_loop() {
    let dir = TempDir::new("ty-trace-mine-counter");
    let (spec_path, _cfg) = write_counter_spec(&dir.path);

    // 1. Generate traces of healthy behavior.
    let (code, gen_stdout, gen_stderr) = run_tla(&[
        "trace-gen",
        spec_path.to_str().unwrap(),
        "--mode",
        "random",
        "--count",
        "3",
        "--max-depth",
        "8",
        "--format",
        "json",
    ]);
    assert_ok(code, &gen_stdout, &gen_stderr);
    let traces_path = dir.path.join("counter-traces.json");
    common::write_file(&traces_path, gen_stdout.as_bytes());

    // 2. Mine a candidate spec; the closed loop must succeed.
    let out_dir = dir.path.join("mined");
    let (code, stdout, stderr) = run_tla(&[
        "trace",
        "mine",
        traces_path.to_str().unwrap(),
        "--module-name",
        "MinedCounter",
        "--out",
        out_dir.to_str().unwrap(),
    ]);
    assert_ok(code, &stdout, &stderr);

    // (c) Recovered candidates: domain 0..5, the +1 update with its
    // observation-boundary guard, and monotonicity.
    assert_contains(
        &stdout,
        &[
            "x \\in 0..5",
            "x' = x + 1",
            "guard: x <= 4",
            "survived TypeOK_x",
            "survived x_Monotone == [][x' >= x]_vars",
            "check: PASS",
        ],
    );

    // (b) Every generating trace validated against the mined spec.
    for k in 1..=3 {
        assert_contains(&stdout, &[&format!("counter-traces.json#{k} — OK")]);
    }
    assert!(!stdout.contains("FAILED"), "{stdout}");

    // (a) The emitted artifacts check clean under the real subcommand.
    let mined_spec = out_dir.join("MinedCounter.tla");
    let mined_cfg = out_dir.join("MinedCounter.cfg");
    assert!(mined_spec.exists() && mined_cfg.exists());
    let (code, check_stdout, check_stderr) = run_tla(&[
        "check",
        mined_spec.to_str().unwrap(),
        "--config",
        mined_cfg.to_str().unwrap(),
    ]);
    assert_ok(code, &check_stdout, &check_stderr);
}

/// Hand-written labeled traces of two interleaved counters: the observed
/// states all satisfy `y <= x`, but the mined actions recombine to refute
/// it — counterexample-guided pruning must drop the relation, and the input
/// traces must still validate via the real `ty trace validate` subcommand.
#[cfg_attr(test, ntest::timeout(120000))]
#[test]
fn mine_prunes_refuted_relation_and_validates_corpus() {
    let dir = TempDir::new("ty-trace-mine-prune");
    let t1 = dir.path.join("t1.json");
    let t2 = dir.path.join("t2.json");
    common::write_file(
        &t1,
        br#"{"version":"1","module":"TwoCounter","variables":["x","y"],"steps":[
 {"index":0,"state":{"x":{"type":"int","value":0},"y":{"type":"int","value":0}}},
 {"index":1,"state":{"x":{"type":"int","value":1},"y":{"type":"int","value":0}},"action":{"name":"IncX"}},
 {"index":2,"state":{"x":{"type":"int","value":1},"y":{"type":"int","value":1}},"action":{"name":"IncY"}}]}
"#,
    );
    common::write_file(
        &t2,
        br#"{"version":"1","module":"TwoCounter","variables":["x","y"],"steps":[
 {"index":0,"state":{"x":{"type":"int","value":1},"y":{"type":"int","value":1}}},
 {"index":1,"state":{"x":{"type":"int","value":2},"y":{"type":"int","value":1}},"action":{"name":"IncX"}},
 {"index":2,"state":{"x":{"type":"int","value":2},"y":{"type":"int","value":2}},"action":{"name":"IncY"}}]}
"#,
    );

    let out_dir = dir.path.join("mined");
    let (code, stdout, stderr) = run_tla(&[
        "trace",
        "mine",
        t1.to_str().unwrap(),
        t2.to_str().unwrap(),
        "--module-name",
        "MinedTwo",
        "--out",
        out_dir.to_str().unwrap(),
    ]);
    assert_ok(code, &stdout, &stderr);

    // The refuted relation was pruned; domains and monotonicity survived.
    assert_contains(
        &stdout,
        &[
            "dropped Rel_x_y (round 1",
            "survived TypeOK_x",
            "survived TypeOK_y",
            "survived x_Monotone",
            "survived y_Monotone",
            "check: PASS",
            "t1.json — OK",
            "t2.json — OK",
        ],
    );
    // Labeled clusters become actions under their observed names.
    assert_contains(&stdout, &["IncX (label \"IncX\"", "IncY (label \"IncY\""]);

    // (b) via the real subcommand: the corpus validates against the mined spec.
    let mined_spec = out_dir.join("MinedTwo.tla");
    let mined_cfg = out_dir.join("MinedTwo.cfg");
    for trace in [&t1, &t2] {
        let (code, val_stdout, val_stderr) = run_tla(&[
            "trace",
            "validate",
            trace.to_str().unwrap(),
            "--spec",
            mined_spec.to_str().unwrap(),
            "--config",
            mined_cfg.to_str().unwrap(),
            "--allow-partial-observations",
        ]);
        assert_ok(code, &val_stdout, &val_stderr);
        assert_contains(&val_stdout, &["OK: trace validated (3 steps"]);
    }
}

/// The `ty init` mutex template exercises non-integer values: function-valued
/// `pc` (TLC `:>`/`@@` literals) and model-value `turn` (mined `CONSTANTS`).
#[cfg_attr(test, ntest::timeout(120000))]
#[test]
fn mine_from_trace_gen_mutex_template_closes_the_loop() {
    let dir = TempDir::new("ty-trace-mine-mutex");
    let (code, init_stdout, init_stderr) = run_tla(&[
        "init",
        "Mutex",
        "--template",
        "mutex",
        "--dir",
        dir.path.to_str().unwrap(),
    ]);
    assert_ok(code, &init_stdout, &init_stderr);

    let spec_path = dir.path.join("Mutex.tla");
    let (code, gen_stdout, gen_stderr) = run_tla(&[
        "trace-gen",
        spec_path.to_str().unwrap(),
        "--mode",
        "random",
        "--count",
        "3",
        "--max-depth",
        "6",
        "--format",
        "json",
    ]);
    assert_ok(code, &gen_stdout, &gen_stderr);
    let traces_path = dir.path.join("mutex-traces.json");
    common::write_file(&traces_path, gen_stdout.as_bytes());

    let out_dir = dir.path.join("mined");
    let (code, stdout, stderr) = run_tla(&[
        "trace",
        "mine",
        traces_path.to_str().unwrap(),
        "--module-name",
        "MinedMutex",
        "--out",
        out_dir.to_str().unwrap(),
    ]);
    assert_ok(code, &stdout, &stderr);
    assert_contains(
        &stdout,
        &["survived TypeOK_pc", "survived TypeOK_turn", "check: PASS"],
    );
    assert!(!stdout.contains("FAILED"), "{stdout}");

    // Model values became constants; function literals pulled in TLC.
    let module_src =
        std::fs::read_to_string(out_dir.join("MinedMutex.tla")).expect("read mined module");
    assert_contains(&module_src, &["CONSTANTS p1, p2", "EXTENDS TLC"]);

    // (a) standalone check of the emitted artifacts.
    let (code, check_stdout, check_stderr) = run_tla(&[
        "check",
        out_dir.join("MinedMutex.tla").to_str().unwrap(),
        "--config",
        out_dir.join("MinedMutex.cfg").to_str().unwrap(),
    ]);
    assert_ok(code, &check_stdout, &check_stderr);
}

/// `--skip-verify` emits the candidate spec without running the loop.
#[cfg_attr(test, ntest::timeout(60000))]
#[test]
fn mine_skip_verify_emits_without_checking() {
    let dir = TempDir::new("ty-trace-mine-skip");
    let trace = dir.path.join("t.json");
    common::write_file(
        &trace,
        br#"{"version":"1","module":"M","variables":["x"],"steps":[
 {"index":0,"state":{"x":{"type":"int","value":0}}},
 {"index":1,"state":{"x":{"type":"int","value":1}}}]}
"#,
    );
    let out_dir = dir.path.join("mined");
    let (code, stdout, stderr) = run_tla(&[
        "trace",
        "mine",
        trace.to_str().unwrap(),
        "--out",
        out_dir.to_str().unwrap(),
        "--skip-verify",
    ]);
    assert_ok(code, &stdout, &stderr);
    assert_contains(&stdout, &["check: SKIPPED (--skip-verify)"]);
    assert!(out_dir.join("Mined.tla").exists());
    assert!(out_dir.join("Mined.cfg").exists());
}

/// Subcommand help documents the candidate-not-ground-truth contract.
#[cfg_attr(test, ntest::timeout(10000))]
#[test]
fn mine_help_states_candidate_contract() {
    let (code, stdout, stderr) = run_tla(&["trace", "mine", "--help"]);
    assert_ok(code, &stdout, &stderr);
    assert_contains(
        &stdout,
        &[
            "Usage: ty trace mine",
            "--module-name",
            "--max-rounds",
            "--skip-verify",
            "NOT ground truth",
        ],
    );
}
