// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

#![cfg(feature = "ay")]

use std::time::Duration;

mod common;

#[cfg_attr(test, ntest::timeout(10000))]
#[test]
fn vmt_cli_writes_vmt_to_stdout_and_evidence_to_stderr() {
    let dir = common::TempDir::new("vmt-cli-evidence");
    let (spec, cfg) = common::write_spec_and_config(
        &dir,
        "VmtCliEvidence",
        r#"---- MODULE VmtCliEvidence ----
VARIABLE x
Init == x = 0
Next == x' = x + 1
Inv == x >= 0
===="#,
        "INIT Init\nNEXT Next\nINVARIANT Inv\n",
    );

    let (code, stdout, stderr) = common::run_tla_parsed_with_timeout(
        &[
            "vmt",
            spec.to_str().expect("spec path should be UTF-8"),
            "--config",
            cfg.to_str().expect("config path should be UTF-8"),
        ],
        Duration::from_secs(10),
    );

    assert_eq!(
        code, 0,
        "ty vmt should succeed\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert_vmt_stdout(&stdout, &stderr);
    assert_vmt_evidence_stderr(&stderr);
}

fn assert_vmt_stdout(stdout: &str, stderr: &str) {
    assert!(
        stdout.starts_with(";; VMT output generated by TY\n"),
        "stdout should start with the VMT artifact header\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    for expected in [
        "(set-logic QF_LIA)",
        "(declare-fun x () Int)",
        "(declare-fun x_next () Int)",
        "(define-fun .init () Bool (= x 0))",
        "(define-fun .trans () Bool (= x_next (+ x 1)))",
        "(define-fun .prop () Bool (>= x 0))",
    ] {
        assert!(
            stdout.contains(expected),
            "stdout missing VMT fragment `{expected}`\nstdout:\n{stdout}\nstderr:\n{stderr}"
        );
    }
    assert_balanced_smtlib(stdout, stderr);
    for report_fragment in [
        "[vmt-export-evidence]",
        "shared_engine_adoption",
        "prepared_checker_program",
        "VMT export complete",
    ] {
        assert!(
            !stdout.contains(report_fragment),
            "stdout should contain only VMT, not report fragment `{report_fragment}`\nstdout:\n{stdout}\nstderr:\n{stderr}"
        );
    }
}

fn assert_balanced_smtlib(stdout: &str, stderr: &str) {
    let mut depth = 0usize;
    for ch in stdout.chars() {
        match ch {
            '(' => depth += 1,
            ')' => {
                assert!(
                    depth > 0,
                    "stdout has an unmatched closing parenthesis\nstdout:\n{stdout}\nstderr:\n{stderr}"
                );
                depth -= 1;
            }
            _ => {}
        }
    }
    assert_eq!(
        depth, 0,
        "stdout has unmatched opening parenthesis\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
}

fn assert_vmt_evidence_stderr(stderr: &str) {
    let rows = stderr
        .lines()
        .filter_map(|line| line.strip_prefix("[vmt-export-evidence] "))
        .collect::<Vec<_>>();
    assert!(
        rows.len() >= 6,
        "stderr should include the VMT evidence row set\nstderr:\n{stderr}"
    );

    let adoption = find_row(&rows, "shared_engine_adoption");
    // The shared_engine_adoption row describes the shared transition-system engine,
    // so its origin_frontend is canonically `vmt_transition_system` (asserted by the
    // tla-check vmt_export_evidence_rows_validate_shared_engine_adoption test) — not
    // `vmt_interchange`, which is the artifact/identity frontend kind checked below.
    assert_eq!(
        evidence_field(adoption, "origin_frontend"),
        Some("vmt_transition_system")
    );
    assert_eq!(
        evidence_field(adoption, "shared_engine_component"),
        Some("tla_mc_core.prepared_checker_program")
    );
    assert_eq!(
        evidence_field(adoption, "acceptance_test"),
        Some("cargo_test_-p_tla-check_--features_ay_vmt_export_evidence_rows_validate")
    );

    let candidate = find_row(&rows, "prepared_candidate_lane");
    assert_eq!(evidence_field(candidate, "lane_kind"), Some("frontend"));
    assert_eq!(
        evidence_field(candidate, "candidate_key"),
        Some("vmt_export")
    );
    assert_eq!(
        evidence_field(candidate, "artifact_identity"),
        Some("artifact:vmt_interchange:VmtCliEvidence")
    );
    assert_eq!(
        evidence_field(candidate, "fingerprint_scheme"),
        Some("canonical_bytes_sha256")
    );

    let validation = find_row(&rows, "prepared_validation_plan");
    assert_eq!(
        evidence_field(validation, "validation_kind"),
        Some("output_format")
    );
    assert_eq!(evidence_field(validation, "fail_closed"), Some("true"));
    assert_eq!(
        evidence_field(validation, "fingerprint_canonicalization"),
        Some("ty-vmt-export-v1")
    );

    let identity = find_row(&rows, "vmt_export_identity");
    assert_eq!(
        evidence_field(identity, "frontend_kind"),
        Some("vmt_interchange")
    );
    assert_eq!(
        evidence_field(identity, "storage_kind"),
        Some("smt_variables")
    );
    assert_eq!(
        evidence_field(identity, "transition_system_kind"),
        Some("exported_transition_system")
    );
    assert_eq!(evidence_field(identity, "output_format"), Some("vmt"));
    assert_eq!(
        evidence_field(identity, "validation_status"),
        Some("validator_backed")
    );
    assert_eq!(evidence_field(identity, "variables"), Some("1"));
    assert_eq!(evidence_field(identity, "invariants"), Some("1"));

    assert!(
        stderr.contains("VMT export complete: 1 variable(s), 1 invariant(s)"),
        "stderr should include the CLI completion summary\nstderr:\n{stderr}"
    );
}

fn find_row<'a>(rows: &'a [&str], kind: &str) -> &'a str {
    rows.iter()
        .copied()
        .find(|row| row.split_whitespace().nth(1) == Some(kind))
        .unwrap_or_else(|| panic!("missing VMT evidence row kind `{kind}`\nrows:\n{rows:#?}"))
}

fn evidence_field<'a>(row: &'a str, field: &str) -> Option<&'a str> {
    let prefix = format!("{field}=");
    row.split_whitespace()
        .find_map(|token| token.strip_prefix(&prefix))
}
