// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Generalized Buchi Automaton (GBA) construction from LTL NNF formulas.
//!
//! Implements a simplified GPVW (Gerth-Peled-Vardi-Wolper) on-the-fly
//! construction with transition-based acceptance.
//!
//! ## Acceptance semantics
//!
//! For each Until sub-formula `φ U ψ`, the acceptance condition requires
//! that the run infinitely often visits a state/edge where the Until is
//! "discharged" — i.e., ψ was satisfied. In the standard GPVW formulation,
//! a state q is accepting for `φ U ψ` if:
//!
//! 1. `φ U ψ ∉ q` (the Until is not an obligation of q), **OR**
//! 2. The transition was generated by choosing `ψ` (Branch 1), discharging
//!    the Until obligation at this step.
//!
//! Condition 2 is critical for formulas like `G(X(F(p)))`, where the `G`
//! operator (Release) re-introduces the `F(p)` (Until) obligation at every
//! step via `Next`. Without edge-based acceptance, no state in the G regime
//! can satisfy condition 1, making the acceptance unsatisfiable even when
//! `p` holds infinitely often.

use super::atoms::LtlContext;
use super::nnf::LtlNnf;
use rustc_hash::{FxHashMap, FxHashSet};

/// A state in the GBA, identified by its "next" obligation set.
pub(crate) type GbaStateId = u32;

/// Generalized Buchi Automaton.
pub(crate) struct Gba {
    /// Number of states.
    pub num_states: u32,
    /// Initial transitions from virtual initial node to GBA states (with guards).
    pub initial_transitions: Vec<GbaTransition>,
    /// Transitions: `transitions[state]` = list of (guard, successor).
    /// Guard is a function from system state to bool.
    pub transitions: Vec<Vec<GbaTransition>>,
    /// Acceptance sets: for each Until sub-formula, the set of GBA states
    /// where the acceptance condition is satisfied (state-based acceptance).
    pub acceptance: Vec<FxHashSet<GbaStateId>>,
}

pub(crate) struct GbaTransition {
    /// Which atoms must hold (positive) or not hold (negative) in the system state.
    pub pos_atoms: Vec<usize>,
    pub neg_atoms: Vec<usize>,
    /// Successor GBA state.
    pub successor: GbaStateId,
    /// Edge-based acceptance: `edge_accept[i]` is true if this transition
    /// discharges Until sub-formula `i` (took Branch 1 for that Until during
    /// expansion). Used together with state-based acceptance for correct
    /// handling of `G(X(F(...)))` patterns.
    pub edge_accept: Vec<bool>,
}

impl GbaTransition {
    pub fn guard_satisfied(&self, ctx: &LtlContext<'_>, sys_state: u32) -> bool {
        self.pos_atoms.iter().all(|&a| ctx.atom_holds(a, sys_state))
            && self
                .neg_atoms
                .iter()
                .all(|&a| !ctx.atom_holds(a, sys_state))
    }
}

impl Gba {
    /// Per-state **reachability-closed** guard-atom sets, for per-Büchi-state
    /// LTL POR visibility (MCC port-plan P2).
    ///
    /// For each GBA state `q`, returns the union of guard atoms (positive AND
    /// negative) over every outgoing transition of every GBA state reachable
    /// from `q` — including `q` itself.
    ///
    /// ## Why this exact set (soundness)
    ///
    /// The C2 ample condition needs every ample transition to be invisible to
    /// every guard the product can ever consult **from this node onward**, so
    /// that the classical exchange/commutation induction (Peled 1996) goes
    /// through node-by-node. Two strictly smaller candidates are UNSOUND:
    ///
    /// 1. **Progressing-edge atoms only** (verifypn `GuardInfo._progressing`,
    ///    transplanted naively into a C2 test): a transition invisible to the
    ///    progressing guards may still falsify the *retarding* (self-loop)
    ///    guard, stranding the product in a node where no outgoing GBA edge is
    ///    enabled — erasing a genuine accepting run (counterexample: ψ = r U p
    ///    with an ample transition that kills `r`).
    /// 2. **All outgoing-edge atoms of the current state only** (no closure):
    ///    a transition invisible to the current state's guards may falsify an
    ///    atom that only appears on the edges of a *later* Büchi state crossed
    ///    after commutation (the "crossing" counterexample, ψ =
    ///    (z R (z∧y)) ∧ (b U (¬z∧c)) — `c` appears on no edge of the
    ///    conjunction state).
    ///
    /// Reachability closure fixes both: retarding edges are included (a
    /// self-loop makes `q` reachable from itself trivially; its atoms are in
    /// `atoms(q)` regardless), and every later-consulted guard belongs to a
    /// state reachable from `q`. The result is **monotone** — `q'` reachable
    /// from `q` implies `ReachVis(q') ⊆ ReachVis(q)` — and always a subset of
    /// the whole-formula atom set, so per-state visibility can only *remove*
    /// visibility relative to the static whole-formula visible set.
    pub(crate) fn per_state_reachable_atoms(&self) -> Vec<FxHashSet<usize>> {
        let n = self.num_states as usize;

        // Local per-state atom sets: union over ALL outgoing edges
        // (progressing and retarding alike).
        let mut rows: Vec<FxHashSet<usize>> = vec![FxHashSet::default(); n];
        for (q, trans) in self.transitions.iter().enumerate() {
            for t in trans {
                rows[q].extend(t.pos_atoms.iter().copied());
                rows[q].extend(t.neg_atoms.iter().copied());
            }
        }

        // Transitive closure over GBA reachability via fixpoint iteration.
        // GBAs are formula-sized (tiny), so a simple sweep-until-stable is
        // cheaper and simpler than an SCC condensation.
        loop {
            let mut changed = false;
            for q in 0..n {
                let mut add: Vec<usize> = Vec::new();
                for t in &self.transitions[q] {
                    let succ = t.successor as usize;
                    if succ == q || succ >= n {
                        continue;
                    }
                    for &a in &rows[succ] {
                        if !rows[q].contains(&a) {
                            add.push(a);
                        }
                    }
                }
                if !add.is_empty() {
                    changed = true;
                    rows[q].extend(add);
                }
            }
            if !changed {
                break;
            }
        }

        rows
    }
}

/// Packed per-acceptance-set membership masks, derived once from a [`Gba`]
/// and shared by the explicit product builders (audit sink S3).
///
/// The `num_accept` acceptance-set bits (one per Until sub-formula, typically
/// 1–3) are packed into `num_words = num_accept.div_ceil(64)` little-endian
/// `u64` words — bit `i` of a stride ⇔ membership in acceptance set `i` — so
/// per-product-state and per-product-edge acceptance is stored as inline
/// words instead of one heap-allocated `Vec<bool>` per state/edge. One
/// uniform representation for every `num_accept` (0 sets ⇒ 0 words), so
/// there is no separate >64-set fallback path through the trusted
/// accepting-SCC logic.
///
/// Losslessness is asserted bit-for-bit against the `Gba`'s own
/// `acceptance` sets and `edge_accept` vectors by `gba_tests`.
pub(crate) struct AcceptanceMasks {
    pub(crate) num_accept: usize,
    pub(crate) num_words: usize,
    /// Per GBA state, strided by `num_words`:
    /// bit `i` of `state_words[q*num_words ..]` ⇔ `acceptance[i].contains(q)`.
    state_words: Vec<u64>,
    /// Per GBA state, per outgoing transition (same order as
    /// `gba.transitions[q]`), strided by `num_words`: the packed
    /// `edge_accept` flags of that transition.
    edge_words: Vec<Vec<u64>>,
}

impl AcceptanceMasks {
    pub(crate) fn from_gba(gba: &Gba) -> Self {
        let num_accept = gba.acceptance.len();
        let num_words = num_accept.div_ceil(64);
        let n = gba.num_states as usize;
        let mut state_words = vec![0u64; n * num_words];
        for (i, set) in gba.acceptance.iter().enumerate() {
            for &q in set {
                let q = q as usize;
                debug_assert!(q < n, "acceptance set {i} references unknown GBA state {q}");
                if q < n {
                    state_words[q * num_words + i / 64] |= 1u64 << (i % 64);
                }
            }
        }
        let edge_words = gba
            .transitions
            .iter()
            .map(|row| {
                let mut words = vec![0u64; row.len() * num_words];
                for (e, t) in row.iter().enumerate() {
                    // The GBA always sets `edge_accept` to length
                    // `num_accept`; `.take` mirrors the former
                    // `.get(i).unwrap_or(false)` defensiveness.
                    for (i, &b) in t.edge_accept.iter().take(num_accept).enumerate() {
                        if b {
                            words[e * num_words + i / 64] |= 1u64 << (i % 64);
                        }
                    }
                }
                words
            })
            .collect();
        Self {
            num_accept,
            num_words,
            state_words,
            edge_words,
        }
    }

    /// The packed state-acceptance words of GBA state `q` (`num_words` long).
    pub(crate) fn state(&self, q: GbaStateId) -> &[u64] {
        let q = q as usize;
        &self.state_words[q * self.num_words..(q + 1) * self.num_words]
    }

    /// The packed edge-acceptance words of `gba.transitions[q][e]`.
    pub(crate) fn edge(&self, q: GbaStateId, e: usize) -> &[u64] {
        let row = &self.edge_words[q as usize];
        &row[e * self.num_words..(e + 1) * self.num_words]
    }
}

/// Bit `i` of a `num_words`-strided acceptance-word slice.
#[inline]
pub(crate) fn accept_bit(words: &[u64], i: usize) -> bool {
    (words[i / 64] >> (i % 64)) & 1 == 1
}

/// Build a GBA from an NNF LTL formula.
pub(super) fn build_gba(formula: &LtlNnf) -> Gba {
    // Collect all Until sub-formulas for acceptance conditions.
    let mut until_formulas: Vec<LtlNnf> = Vec::new();
    collect_untils(formula, &mut until_formulas);
    let num_accept = until_formulas.len();

    // State map: "next obligation set" → state ID
    let mut state_map: FxHashMap<Vec<LtlNnf>, GbaStateId> = FxHashMap::default();
    let mut transitions: Vec<Vec<GbaTransition>> = Vec::new();
    let mut acceptance: Vec<FxHashSet<GbaStateId>> =
        vec![FxHashSet::default(); until_formulas.len()];

    // Work queue for states to expand
    let mut queue: Vec<Vec<LtlNnf>> = Vec::new();

    // Generate initial transitions by expanding the formula.
    // The "initial state" is virtual — we compute transitions from it
    // to find the actual GBA initial states.
    let mut initial_expansions: Vec<ExpansionResult> = Vec::new();
    expand_formula(
        std::slice::from_ref(formula),
        Vec::new(),
        Vec::new(),
        Vec::new(),
        vec![false; num_accept],
        &until_formulas,
        &mut initial_expansions,
    );

    let mut initial_transitions: Vec<GbaTransition> = Vec::new();
    for exp in &initial_expansions {
        let mut sorted_next = exp.next_obligations.clone();
        sorted_next.sort();
        sorted_next.dedup();

        let sid = get_or_create_state(
            &mut state_map,
            &mut transitions,
            &mut queue,
            &sorted_next,
            &until_formulas,
            &mut acceptance,
        );
        initial_transitions.push(GbaTransition {
            pos_atoms: exp.pos_atoms.clone(),
            neg_atoms: exp.neg_atoms.clone(),
            successor: sid,
            edge_accept: exp.discharged.clone(),
        });
    }

    // BFS to discover all reachable GBA states.
    let mut processed = 0;
    while processed < queue.len() {
        let next_set = queue[processed].clone();
        let sid = state_map[&next_set];
        processed += 1;

        // Expand the formulas in this state's obligation set.
        let mut expansions: Vec<ExpansionResult> = Vec::new();
        if next_set.is_empty() {
            // No obligations — self-loop with no guard (always enabled)
            expansions.push(ExpansionResult {
                pos_atoms: Vec::new(),
                neg_atoms: Vec::new(),
                next_obligations: Vec::new(),
                discharged: vec![false; num_accept],
            });
        } else {
            expand_formula(
                &next_set,
                Vec::new(),
                Vec::new(),
                Vec::new(),
                vec![false; num_accept],
                &until_formulas,
                &mut expansions,
            );
        }

        let mut trans = Vec::new();
        for exp in &expansions {
            let mut sorted = exp.next_obligations.clone();
            sorted.sort();
            sorted.dedup();

            let succ_id = get_or_create_state(
                &mut state_map,
                &mut transitions,
                &mut queue,
                &sorted,
                &until_formulas,
                &mut acceptance,
            );

            trans.push(GbaTransition {
                pos_atoms: exp.pos_atoms.clone(),
                neg_atoms: exp.neg_atoms.clone(),
                successor: succ_id,
                edge_accept: exp.discharged.clone(),
            });
        }
        transitions[sid as usize] = trans;
    }

    Gba {
        num_states: state_map.len() as u32,
        initial_transitions,
        transitions,
        acceptance,
    }
}

fn get_or_create_state(
    state_map: &mut FxHashMap<Vec<LtlNnf>, GbaStateId>,
    transitions: &mut Vec<Vec<GbaTransition>>,
    queue: &mut Vec<Vec<LtlNnf>>,
    next_set: &[LtlNnf],
    until_formulas: &[LtlNnf],
    acceptance: &mut [FxHashSet<GbaStateId>],
) -> GbaStateId {
    let key = next_set.to_vec();
    if let Some(&id) = state_map.get(&key) {
        return id;
    }
    let id = state_map.len() as GbaStateId;
    state_map.insert(key, id);
    transitions.push(Vec::new());
    queue.push(next_set.to_vec());

    // Acceptance: state is accepting for set i if Until formula i
    // is NOT among this state's obligations.
    for (i, uf) in until_formulas.iter().enumerate() {
        if !next_set.contains(uf) {
            acceptance[i].insert(id);
        }
    }

    id
}

/// Collect all Until sub-formulas (for acceptance conditions).
fn collect_untils(formula: &LtlNnf, result: &mut Vec<LtlNnf>) {
    match formula {
        LtlNnf::Until(a, b) => {
            if !result.contains(formula) {
                result.push(formula.clone());
            }
            collect_untils(a, result);
            collect_untils(b, result);
        }
        LtlNnf::Release(a, b) => {
            collect_untils(a, result);
            collect_untils(b, result);
        }
        LtlNnf::And(children) | LtlNnf::Or(children) => {
            for c in children {
                collect_untils(c, result);
            }
        }
        LtlNnf::Next(inner) => collect_untils(inner, result),
        LtlNnf::Atom(_) | LtlNnf::NegAtom(_) | LtlNnf::True | LtlNnf::False => {}
    }
}

/// Result of expanding a set of LTL formulas.
struct ExpansionResult {
    pos_atoms: Vec<usize>,
    neg_atoms: Vec<usize>,
    next_obligations: Vec<LtlNnf>,
    /// Which Until sub-formulas were discharged (Branch 1 taken) during
    /// this expansion path. `discharged[i]` corresponds to `until_formulas[i]`.
    discharged: Vec<bool>,
}

/// Expand a set of LTL formulas into expansion results.
///
/// This is the core of the GPVW algorithm: process each formula to determine
/// what atoms must hold now and what obligations carry to the next step.
/// Also tracks which Until sub-formulas are discharged (Branch 1 taken)
/// for edge-based acceptance.
fn expand_formula(
    to_process: &[LtlNnf],
    pos_atoms: Vec<usize>,
    neg_atoms: Vec<usize>,
    next_obligations: Vec<LtlNnf>,
    discharged: Vec<bool>,
    until_formulas: &[LtlNnf],
    results: &mut Vec<ExpansionResult>,
) {
    if to_process.is_empty() {
        results.push(ExpansionResult {
            pos_atoms,
            neg_atoms,
            next_obligations,
            discharged,
        });
        return;
    }

    let formula = &to_process[0];
    let rest = &to_process[1..];

    match formula {
        LtlNnf::True => {
            expand_formula(
                rest,
                pos_atoms,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::False => {
            // Contradiction — this branch dies
        }
        LtlNnf::Atom(id) => {
            if neg_atoms.contains(id) {
                return; // Contradiction
            }
            let mut new_pos = pos_atoms.clone();
            if !new_pos.contains(id) {
                new_pos.push(*id);
            }
            expand_formula(
                rest,
                new_pos,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::NegAtom(id) => {
            if pos_atoms.contains(id) {
                return; // Contradiction
            }
            let mut new_neg = neg_atoms.clone();
            if !new_neg.contains(id) {
                new_neg.push(*id);
            }
            expand_formula(
                rest,
                pos_atoms,
                new_neg,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::And(children) => {
            let mut combined: Vec<LtlNnf> = children.clone();
            combined.extend_from_slice(rest);
            expand_formula(
                &combined,
                pos_atoms,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::Or(children) => {
            // Nondeterministic choice: try each child
            for child in children {
                let mut branch: Vec<LtlNnf> = vec![child.clone()];
                branch.extend_from_slice(rest);
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    discharged.clone(),
                    until_formulas,
                    results,
                );
            }
        }
        LtlNnf::Next(inner) => {
            let mut new_next = next_obligations.clone();
            new_next.push(*inner.clone());
            expand_formula(
                rest,
                pos_atoms,
                neg_atoms,
                new_next,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::Until(a, b) => {
            // a U b: either b holds now, OR (a holds now AND X(a U b))
            // Branch 1: b holds now (Until discharged)
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone()];
                branch.extend_from_slice(rest);
                // Mark this Until as discharged for edge acceptance
                let mut new_discharged = discharged.clone();
                if let Some(idx) = until_formulas.iter().position(|uf| uf == formula) {
                    new_discharged[idx] = true;
                }
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    new_discharged,
                    until_formulas,
                    results,
                );
            }
            // Branch 2: a holds now, obligation continues
            {
                let mut branch: Vec<LtlNnf> = vec![*a.clone()];
                branch.extend_from_slice(rest);
                let mut new_next = next_obligations.clone();
                new_next.push(formula.clone());
                expand_formula(
                    &branch,
                    pos_atoms,
                    neg_atoms,
                    new_next,
                    discharged,
                    until_formulas,
                    results,
                );
            }
        }
        LtlNnf::Release(a, b) => {
            // a R b: b must hold now, AND (a holds now OR X(a R b))
            // Branch 1: b AND a hold now (release satisfied)
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone(), *a.clone()];
                branch.extend_from_slice(rest);
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    discharged.clone(),
                    until_formulas,
                    results,
                );
            }
            // Branch 2: b holds now, obligation continues
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone()];
                branch.extend_from_slice(rest);
                let mut new_next = next_obligations.clone();
                new_next.push(formula.clone());
                expand_formula(
                    &branch,
                    pos_atoms,
                    neg_atoms,
                    new_next,
                    discharged,
                    until_formulas,
                    results,
                );
            }
        }
    }
}

#[cfg(test)]
#[path = "gba_tests.rs"]
mod gba_tests;
