// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

use crate::marking::{pack_marking_config, MarkingConfig};
use crate::petri_net::{PetriNet, TransitionIdx};
use crate::stubborn::{DependencyGraph, PorStrategy};
use tla_mc_core::{
    CheckerSourceKind, PreparedFingerprintAdmissionPlan, PreparedProgramPayloadKind,
    PreparedStorageKind, PreparedSuccessorBatchDescriptor, PreparedSuccessorPayloadKind,
    PreparedSuccessorProvider, PreparedSuccessorRef, SetupTraceLaneKind,
    SharedEngineFrontendFamily,
};

use super::fingerprint::fingerprint_marking;
use super::transition_selection::{
    enabled_transitions_into, full_scan_enabled_bitmap, incremental_differential_enabled,
    incremental_enabled_disabled, incremental_enabled_update, PlaceConsumerIndex,
};

/// Borrowed successor emitted by a Petri successor provider.
pub(crate) struct PetriSuccessorRef<'a> {
    pub(crate) transition: TransitionIdx,
    /// The marking BEFORE `transition` fired (a.k.a. the source marking).
    /// Required by orbit-quotient observers (e.g. StateSpace under
    /// place-swap canonicalization) that need to multiply each edge
    /// observation by |G·source| to recover the true edge count.
    pub(crate) source: &'a [u64],
    pub(crate) marking: &'a [u64],
    pub(crate) packed: &'a [u8],
    pub(crate) fingerprint: u128,
}

impl<'a> PetriSuccessorRef<'a> {
    pub(crate) fn as_prepared(&self) -> PreparedSuccessorRef<'a, TransitionIdx, u128> {
        PreparedSuccessorRef::new(self.transition)
            .with_fingerprint(self.fingerprint)
            .with_canonical_payload(self.packed)
    }
}

/// Per-state full enabled-set carry threaded through the (sequential, no-POR,
/// non-canonicalizing) BFS queue, enabling the O(Δ) incremental enabledness
/// update on wide/high-transition nets.
///
/// `bits[u]` is `true` iff transition `u` is enabled at the marking this carry
/// is attached to. Stored as an `Arc<[bool]>` so the queue can hold one per
/// frontier state at `T/8`-ish bytes each (lives only between successor
/// generation and pop). Generated by the incremental update keyed off the
/// parent's carry, and seeded at the BFS root by a one-time full scan.
pub(crate) type EnabledCarry = std::sync::Arc<[bool]>;

/// Visitor control for successor enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SuccessorVisit {
    Continue,
    Stop,
}

/// Common interface for Petri successor enumeration.
pub(crate) trait PetriSuccessorProvider {
    fn prepared_successor_batch_descriptor(&self) -> &PreparedSuccessorBatchDescriptor;

    fn for_each_successor(
        &mut self,
        current_marking: &mut Vec<u64>,
        visit: &mut dyn FnMut(PetriSuccessorRef<'_>) -> SuccessorVisit,
    ) -> bool;

    fn has_enabled_successors(&self) -> bool;

    /// Whether a prior [`for_each_successor`](Self::for_each_successor) aborted
    /// because firing a transition would overflow a place's `u64` token count
    /// (#22). A `true` here means the enumeration was incomplete and the caller
    /// must treat the result as CANNOT_COMPUTE rather than a complete frontier.
    /// Default `false`: providers that cannot overflow never set it.
    fn token_overflow_declined(&self) -> bool {
        false
    }
}

/// Interpreted successor provider using the existing Petri transition relation.
use crate::explorer::symmetry::PetriCanonicalizer;
pub(crate) struct InterpretedSuccessorProvider<'a> {
    net: &'a PetriNet,
    marking_config: &'a MarkingConfig,
    num_transitions: usize,
    dep_graph: Option<&'a DependencyGraph>,
    por_strategy: &'a PorStrategy,
    prepared_descriptor: PreparedSuccessorBatchDescriptor,
    enabled_transitions: Vec<TransitionIdx>,
    pack_buf: Vec<u8>,
    successor_scratch: Vec<u64>,
    /// Snapshot of the source marking taken at the top of
    /// `for_each_successor`. Required to provide the source slice to
    /// orbit-quotient observers, since `current_marking` is mutated in
    /// place during enumeration (apply_delta / undo_delta).
    source_scratch: Vec<u64>,
    canonicalizer: Option<super::symmetry::PetriCanonicalizer>,
    /// Set when an `apply_delta`/`fire_into` in `for_each_successor` declined a
    /// token-count overflow (#22); makes the incomplete enumeration observable.
    token_overflow_declined: bool,
    /// Static place→consuming-transition index for the incremental enabled-set
    /// update. Built lazily on first use of the incremental path (so the
    /// non-incremental callers pay nothing).
    place_consumer_index: Option<PlaceConsumerIndex>,
    /// Reusable full enabled bitmap of the CURRENT (parent) state on the
    /// incremental path — the iteration order over enabled transitions.
    enabled_bitmap_scratch: Vec<bool>,
    /// Reusable bitmap holding the child's incrementally-derived enabled set,
    /// handed to the visitor (and, for admitted successors, cloned into the
    /// queue carry by the caller).
    child_enabled_scratch: Vec<bool>,
    /// Reusable per-place "seen this firing" scratch for
    /// [`incremental_enabled_update`]; kept all-`false` between calls.
    seen_places_scratch: Vec<bool>,
    /// Full-scan oracle bitmap, only allocated/used when the per-state
    /// differential verification is active.
    differential_scratch: Vec<bool>,
}

impl<'a> InterpretedSuccessorProvider<'a> {
    pub(crate) fn canonicalizer(&self) -> Option<&PetriCanonicalizer> {
        self.canonicalizer.as_ref()
    }

    pub(crate) fn new(
        net: &'a PetriNet,
        marking_config: &'a MarkingConfig,
        pack_capacity: usize,
        num_transitions: usize,
        dep_graph: Option<&'a DependencyGraph>,
        por_strategy: &'a PorStrategy,
        canonicalizer: Option<super::symmetry::PetriCanonicalizer>,
    ) -> Self {
        Self {
            net,
            marking_config,
            num_transitions,
            dep_graph,
            por_strategy,
            prepared_descriptor: prepared_petri_successor_batch_descriptor(),
            enabled_transitions: Vec::with_capacity(num_transitions),
            pack_buf: Vec::with_capacity(pack_capacity),
            successor_scratch: Vec::with_capacity(net.num_places()),
            source_scratch: Vec::with_capacity(net.num_places()),
            canonicalizer,
            token_overflow_declined: false,
            place_consumer_index: None,
            enabled_bitmap_scratch: Vec::new(),
            child_enabled_scratch: Vec::new(),
            seen_places_scratch: Vec::new(),
            differential_scratch: Vec::new(),
        }
    }

    /// Whether the incremental enabled-set path is admissible for THIS provider.
    ///
    /// Sound only when:
    /// - the kill-switch env (`TY_MCC_DISABLE_INCREMENTAL_ENABLED`) is unset,
    /// - no symmetry canonicalizer is installed (canonicalization place-permutes
    ///   the emitted successor marking, so the enabled set incrementally derived
    ///   at `fire(parent, t)` would NOT match the enabled set of the canonical
    ///   representative actually enqueued — the carry would be wrong), and
    /// - partial-order reduction is off (`dep_graph` is `None`): with POR,
    ///   `enabled_transitions_into` returns a stubborn SUBSET, not the full
    ///   enabled set, so neither the iteration order nor the carry is the full
    ///   enabled set the incremental delta requires.
    ///
    /// When this returns `false` the incremental entry points transparently fall
    /// back to the proven full-scan path; the carry they emit is then a correct
    /// full-scan bitmap, but the caller must drop it (treat the next state's
    /// carry as `None`) since the gate may differ per state only via the env
    /// kill-switch (which is process-global, so in practice it is stable).
    pub(crate) fn incremental_enabled_admissible(&self) -> bool {
        !incremental_enabled_disabled() && self.canonicalizer.is_none() && self.dep_graph.is_none()
    }

    /// Full-scan enabled bitmap of `marking` for every transition — used to seed
    /// the incremental carry at the BFS root.
    pub(crate) fn full_enabled_bitmap(&self, marking: &[u64]) -> Vec<bool> {
        let mut out = Vec::new();
        full_scan_enabled_bitmap(self.net, marking, self.num_transitions, &mut out);
        out
    }

    /// Enumerate successors of `current_marking`, carrying the parent's full
    /// enabled bitmap and emitting each child's full enabled bitmap.
    ///
    /// This is the INCREMENTAL counterpart to
    /// [`PetriSuccessorProvider::for_each_successor`]: instead of an `O(T)`
    /// per-state enabledness re-scan, when `parent_enabled` is supplied and the
    /// fast path is admissible ([`Self::incremental_enabled_admissible`]) the
    /// parent's enabled set is taken as the iteration order directly (no scan),
    /// and each child's enabled set is derived in `O(Δ)` — re-evaluating only the
    /// transitions consuming from a place the fired transition changed.
    ///
    /// `visit` receives each successor ref AND that successor's full enabled
    /// bitmap (`&[bool]`, length = num transitions). The caller stores this
    /// bitmap as the queue carry for admitted successors so it becomes the next
    /// state's `parent_enabled`.
    ///
    /// Soundness contract (verified per-state under
    /// [`incremental_differential_enabled`]): the enabled set this method uses /
    /// emits is BIT-FOR-BIT identical to a full scan via
    /// [`enabled_transitions_into`] / [`full_scan_enabled_bitmap`]. If the fast
    /// path is not admissible, or `parent_enabled` is `None`/wrong-length, it
    /// transparently full-scans — never a divergent set.
    ///
    /// Returns `true` if enumeration completed (no `Stop`, no token overflow).
    pub(crate) fn for_each_successor_with_enabled(
        &mut self,
        current_marking: &mut Vec<u64>,
        parent_enabled: Option<&[bool]>,
        visit: &mut dyn FnMut(PetriSuccessorRef<'_>, &[bool]) -> SuccessorVisit,
    ) -> bool {
        self.token_overflow_declined = false;

        // The incremental fast path requires: admissible provider (no POR / no
        // canonicalizer / kill-switch off) AND a correctly-sized parent carry.
        // The canonicalizer is statically absent on every caller of this method
        // (fingerprint-only is never symmetric; the sequential exact path gates
        // on `canonicalizer.is_none()` before calling), but we recheck for
        // defence-in-depth.
        let use_incremental = self.incremental_enabled_admissible()
            && parent_enabled.is_some_and(|bits| bits.len() == self.num_transitions);

        if !use_incremental {
            // Fall back to the proven full-scan enumeration. We still emit each
            // child's full-scan enabled bitmap so the caller's signature is
            // uniform, but the caller must NOT carry it forward (it drops to a
            // `None` parent carry on the next state).
            return self.for_each_successor_full_scan_emit(current_marking, visit);
        }

        let parent_enabled = parent_enabled.expect("checked is_some above");

        // Iterate the parent's enabled transitions directly from the carry — no
        // O(T) scan. Materialize the index list into `enabled_transitions` so
        // `has_enabled_successors` and the differential check observe the same
        // set the non-incremental path would.
        self.enabled_transitions.clear();
        for (tidx, &on) in parent_enabled.iter().enumerate() {
            if on {
                self.enabled_transitions.push(TransitionIdx(tidx as u32));
            }
        }

        // Per-state differential: assert the carry equals a fresh full scan of
        // the parent. Catches any upstream carry corruption immediately.
        if incremental_differential_enabled() {
            full_scan_enabled_bitmap(
                self.net,
                current_marking,
                self.num_transitions,
                &mut self.differential_scratch,
            );
            assert!(
                self.differential_scratch.as_slice() == parent_enabled,
                "incremental enabled carry diverged from full scan at parent marking"
            );
        }

        // Snapshot source (current_marking is mutated in place below).
        self.source_scratch.clear();
        self.source_scratch.extend_from_slice(current_marking);

        // Ensure the per-place seen scratch is sized and clean.
        if self.seen_places_scratch.len() != self.net.num_places() {
            self.seen_places_scratch = vec![false; self.net.num_places()];
        }

        let index = match self.place_consumer_index.take() {
            Some(idx) => idx,
            None => PlaceConsumerIndex::build(self.net),
        };

        let mut completed = true;
        // Iterate by raw index so we can borrow `self` mutably for scratch while
        // reading `enabled_transitions` (which we do not mutate in the loop).
        let enabled_len = self.enabled_transitions.len();
        for i in 0..enabled_len {
            let transition = self.enabled_transitions[i];

            // Fire in place. Fail-closed on token overflow (#22): the marking is
            // partially mutated, so do NOT undo — abort and flag the decline.
            if self
                .net
                .apply_delta(current_marking.as_mut_slice(), transition)
                .is_err()
            {
                self.token_overflow_declined = true;
                completed = false;
                break;
            }

            // Child marking is live in `current_marking` between apply/undo.
            // Derive the child's full enabled bitmap incrementally.
            incremental_enabled_update(
                self.net,
                &index,
                parent_enabled,
                current_marking,
                transition,
                &mut self.seen_places_scratch,
                &mut self.child_enabled_scratch,
            );

            // Per-state differential on the CHILD bitmap.
            if incremental_differential_enabled() {
                full_scan_enabled_bitmap(
                    self.net,
                    current_marking,
                    self.num_transitions,
                    &mut self.differential_scratch,
                );
                assert!(
                    self.differential_scratch == self.child_enabled_scratch,
                    "incremental child enabled set diverged from full scan after firing {transition:?}"
                );
            }

            pack_marking_config(current_marking, self.marking_config, &mut self.pack_buf);
            let fingerprint = fingerprint_marking(&self.pack_buf);

            let decision = visit(
                PetriSuccessorRef {
                    transition,
                    source: &self.source_scratch,
                    marking: current_marking,
                    packed: &self.pack_buf,
                    fingerprint,
                },
                &self.child_enabled_scratch,
            );

            self.net
                .undo_delta(current_marking.as_mut_slice(), transition);

            if decision == SuccessorVisit::Stop {
                completed = false;
                break;
            }
        }

        // Restore the index (it is `&self`-static; reuse across states).
        self.place_consumer_index = Some(index);
        completed
    }

    /// Full-scan enumeration matching [`PetriSuccessorProvider::for_each_successor`]
    /// exactly, but with the incremental caller's two-argument visitor signature.
    /// Used when the incremental fast path is NOT admissible (POR on, or a
    /// canonicalizer is installed, or the kill-switch is set). Preserves the
    /// original soundness (#22 token-overflow handling, source snapshot,
    /// canonicalize-before-pack, undo).
    ///
    /// The per-child enabled bitmap is NOT computed here: this path is only
    /// reached when the caller will discard the carry (it sets the next state's
    /// carry to `None`), so the visitor receives an EMPTY slice as a sentinel.
    /// This keeps the canonicalizer/POR path's per-state cost identical to the
    /// original `for_each_successor` — the incremental optimization adds no
    /// overhead to the paths it does not accelerate.
    fn for_each_successor_full_scan_emit(
        &mut self,
        current_marking: &mut Vec<u64>,
        visit: &mut dyn FnMut(PetriSuccessorRef<'_>, &[bool]) -> SuccessorVisit,
    ) -> bool {
        enabled_transitions_into(
            self.net,
            current_marking,
            self.num_transitions,
            self.dep_graph,
            self.por_strategy,
            &mut self.enabled_transitions,
        );

        self.source_scratch.clear();
        self.source_scratch.extend_from_slice(current_marking);

        let enabled_len = self.enabled_transitions.len();
        for i in 0..enabled_len {
            let transition = self.enabled_transitions[i];
            if let Some(canonicalizer) = &self.canonicalizer {
                if self
                    .net
                    .fire_into(current_marking, transition, &mut self.successor_scratch)
                    .is_err()
                {
                    self.token_overflow_declined = true;
                    return false;
                }
                canonicalizer.canonicalize(&mut self.successor_scratch);
                pack_marking_config(
                    &self.successor_scratch,
                    self.marking_config,
                    &mut self.pack_buf,
                );
                let fingerprint = fingerprint_marking(&self.pack_buf);

                let decision = visit(
                    PetriSuccessorRef {
                        transition,
                        source: &self.source_scratch,
                        marking: &self.successor_scratch,
                        packed: &self.pack_buf,
                        fingerprint,
                    },
                    &[],
                );
                if decision == SuccessorVisit::Stop {
                    return false;
                }
                continue;
            }

            if self
                .net
                .apply_delta(current_marking.as_mut_slice(), transition)
                .is_err()
            {
                self.token_overflow_declined = true;
                return false;
            }
            pack_marking_config(current_marking, self.marking_config, &mut self.pack_buf);
            let fingerprint = fingerprint_marking(&self.pack_buf);

            let decision = visit(
                PetriSuccessorRef {
                    transition,
                    source: &self.source_scratch,
                    marking: current_marking,
                    packed: &self.pack_buf,
                    fingerprint,
                },
                &[],
            );

            self.net
                .undo_delta(current_marking.as_mut_slice(), transition);

            if decision == SuccessorVisit::Stop {
                return false;
            }
        }

        true
    }
}

impl PetriSuccessorProvider for InterpretedSuccessorProvider<'_> {
    fn prepared_successor_batch_descriptor(&self) -> &PreparedSuccessorBatchDescriptor {
        &self.prepared_descriptor
    }

    fn for_each_successor(
        &mut self,
        current_marking: &mut Vec<u64>,
        visit: &mut dyn FnMut(PetriSuccessorRef<'_>) -> SuccessorVisit,
    ) -> bool {
        self.token_overflow_declined = false;
        enabled_transitions_into(
            self.net,
            current_marking,
            self.num_transitions,
            self.dep_graph,
            self.por_strategy,
            &mut self.enabled_transitions,
        );

        // Snapshot the source marking so we can hand it out via
        // `PetriSuccessorRef::source` even after `apply_delta` mutates
        // `current_marking` in the delta-based code path below.
        self.source_scratch.clear();
        self.source_scratch.extend_from_slice(current_marking);

        for &transition in &self.enabled_transitions {
            if let Some(canonicalizer) = &self.canonicalizer {
                // Fail-closed (#22): on token-count overflow stop enumerating and
                // flag the decline so the caller treats the frontier as
                // incomplete (CANNOT_COMPUTE), never a complete-but-wrong set.
                if self
                    .net
                    .fire_into(current_marking, transition, &mut self.successor_scratch)
                    .is_err()
                {
                    self.token_overflow_declined = true;
                    return false;
                }
                canonicalizer.canonicalize(&mut self.successor_scratch);
                pack_marking_config(
                    &self.successor_scratch,
                    self.marking_config,
                    &mut self.pack_buf,
                );
                let fingerprint = fingerprint_marking(&self.pack_buf);

                let decision = visit(PetriSuccessorRef {
                    transition,
                    source: &self.source_scratch,
                    marking: &self.successor_scratch,
                    packed: &self.pack_buf,
                    fingerprint,
                });

                if decision == SuccessorVisit::Stop {
                    return false;
                }
                continue;
            }

            // Fail-closed (#22): a token-count overflow leaves `current_marking`
            // partially mutated, so we must NOT undo. Flag the decline and abort
            // — the caller treats the frontier as incomplete (CANNOT_COMPUTE).
            if self
                .net
                .apply_delta(current_marking.as_mut_slice(), transition)
                .is_err()
            {
                self.token_overflow_declined = true;
                return false;
            }
            pack_marking_config(current_marking, self.marking_config, &mut self.pack_buf);
            let fingerprint = fingerprint_marking(&self.pack_buf);

            let decision = visit(PetriSuccessorRef {
                transition,
                source: &self.source_scratch,
                marking: current_marking,
                packed: &self.pack_buf,
                fingerprint,
            });

            self.net
                .undo_delta(current_marking.as_mut_slice(), transition);

            if decision == SuccessorVisit::Stop {
                return false;
            }
        }

        true
    }

    fn has_enabled_successors(&self) -> bool {
        !self.enabled_transitions.is_empty()
    }

    fn token_overflow_declined(&self) -> bool {
        self.token_overflow_declined
    }
}

impl PreparedSuccessorProvider<Vec<u64>> for InterpretedSuccessorProvider<'_> {
    type Action = TransitionIdx;
    type Fingerprint = u128;

    fn prepared_successor_batch_descriptor(&self) -> &PreparedSuccessorBatchDescriptor {
        &self.prepared_descriptor
    }

    fn for_each_prepared_successor(
        &mut self,
        state: &mut Vec<u64>,
        visit: &mut dyn FnMut(PreparedSuccessorRef<'_, Self::Action, Self::Fingerprint>) -> bool,
    ) -> bool {
        self.for_each_successor(state, &mut |successor| {
            if visit(successor.as_prepared()) {
                SuccessorVisit::Continue
            } else {
                SuccessorVisit::Stop
            }
        })
    }
}

pub(crate) fn prepared_petri_successor_batch_descriptor() -> PreparedSuccessorBatchDescriptor {
    PreparedSuccessorBatchDescriptor::new(
        "mcc_petri.interpreted.prepared_successor_batch.v1",
        CheckerSourceKind::MccPetri,
        PreparedProgramPayloadKind::MccPetri,
        PreparedStorageKind::PetriMarking,
        SetupTraceLaneKind::ExplicitState,
        PreparedSuccessorPayloadKind::CanonicalPayloadOnly,
    )
    .with_candidate_key("interpreted_successor_provider")
    .with_prepared_program_identity("mcc_petri.prepared_marking.interpreted.v1")
    .with_prepared_lane_identity("mcc_petri.explicit_state.prepared_successor_lane.v1")
    .with_batch_artifact_identity("mcc_petri.interpreted.successor_batch.artifact.v1")
    .with_admission_plan(PreparedFingerprintAdmissionPlan::petri_marking_cas(
        "mcc_petri.interpreted.successor_batch.prepared_fingerprint_admission.v1",
        "pack_marking_config.v1",
    ))
    .with_frontend_families(
        [SharedEngineFrontendFamily::MccPetri],
        [SharedEngineFrontendFamily::MccPetri],
    )
}

#[cfg(test)]
mod tests {
    use crate::marking::pack_marking_config;
    use crate::petri_net::{Arc, PetriNet, PlaceIdx, PlaceInfo, TransitionInfo};
    use crate::stubborn::PorStrategy;

    use super::*;
    use crate::explorer::setup::ExplorationSetup;

    fn branching_net() -> PetriNet {
        PetriNet {
            name: Some("branching".into()),
            places: vec![
                PlaceInfo {
                    id: "p0".into(),
                    name: None,
                },
                PlaceInfo {
                    id: "p1".into(),
                    name: None,
                },
                PlaceInfo {
                    id: "p2".into(),
                    name: None,
                },
            ],
            transitions: vec![
                TransitionInfo {
                    id: "t0".into(),
                    name: None,
                    inputs: vec![Arc {
                        place: PlaceIdx(0),
                        weight: 1,
                    }],
                    outputs: vec![Arc {
                        place: PlaceIdx(1),
                        weight: 1,
                    }],
                },
                TransitionInfo {
                    id: "t1".into(),
                    name: None,
                    inputs: vec![Arc {
                        place: PlaceIdx(0),
                        weight: 1,
                    }],
                    outputs: vec![Arc {
                        place: PlaceIdx(2),
                        weight: 1,
                    }],
                },
            ],
            initial_marking: vec![1, 0, 0],
        }
    }

    fn symmetric_sink_net() -> PetriNet {
        PetriNet {
            name: Some("symmetric-sink".into()),
            places: vec![
                PlaceInfo {
                    id: "p0".into(),
                    name: None,
                },
                PlaceInfo {
                    id: "p1".into(),
                    name: None,
                },
                PlaceInfo {
                    id: "sink".into(),
                    name: None,
                },
            ],
            transitions: vec![
                TransitionInfo {
                    id: "t0".into(),
                    name: None,
                    inputs: vec![Arc {
                        place: PlaceIdx(0),
                        weight: 1,
                    }],
                    outputs: vec![Arc {
                        place: PlaceIdx(2),
                        weight: 1,
                    }],
                },
                TransitionInfo {
                    id: "t1".into(),
                    name: None,
                    inputs: vec![Arc {
                        place: PlaceIdx(1),
                        weight: 1,
                    }],
                    outputs: vec![Arc {
                        place: PlaceIdx(2),
                        weight: 1,
                    }],
                },
            ],
            initial_marking: vec![1, 1, 0],
        }
    }

    #[test]
    fn interpreted_provider_matches_direct_fire_for_tiny_net() {
        let net = branching_net();
        let setup = ExplorationSetup::analyze(&net);
        let por_strategy = PorStrategy::None;
        let mut provider = InterpretedSuccessorProvider::new(
            &net,
            &setup.marking_config,
            setup.pack_capacity,
            setup.num_transitions,
            None,
            &por_strategy,
            None,
        );
        let mut current_marking = net.initial_marking.clone();
        let mut observed = Vec::new();

        let completed = provider.for_each_successor(&mut current_marking, &mut |successor| {
            observed.push((
                successor.transition,
                successor.marking.to_vec(),
                successor.packed.to_vec(),
                successor.fingerprint,
            ));
            SuccessorVisit::Continue
        });

        let mut expected = Vec::new();
        for tidx in 0..net.num_transitions() {
            let transition = TransitionIdx(tidx as u32);
            if !net.is_enabled(&net.initial_marking, transition) {
                continue;
            }
            let marking = net
                .fire(&net.initial_marking, transition)
                .expect("fire (test)");
            let mut packed = Vec::with_capacity(setup.pack_capacity);
            pack_marking_config(&marking, &setup.marking_config, &mut packed);
            let fingerprint = fingerprint_marking(&packed);
            expected.push((transition, marking, packed, fingerprint));
        }

        assert!(completed);
        assert!(provider.has_enabled_successors());
        assert_eq!(current_marking, net.initial_marking);
        assert_eq!(observed, expected);
    }

    #[test]
    fn interpreted_provider_emits_prepared_successor_refs() {
        let net = branching_net();
        let setup = ExplorationSetup::analyze(&net);
        let por_strategy = PorStrategy::None;
        let mut provider = InterpretedSuccessorProvider::new(
            &net,
            &setup.marking_config,
            setup.pack_capacity,
            setup.num_transitions,
            None,
            &por_strategy,
            None,
        );
        let mut current_marking = net.initial_marking.clone();
        let mut prepared = Vec::new();

        assert!(PreparedSuccessorProvider::for_each_prepared_successor(
            &mut provider,
            &mut current_marking,
            &mut |successor| {
                prepared.push((
                    successor.action,
                    successor.fingerprint,
                    successor.canonical_payload.map(<[u8]>::to_vec),
                    successor.full_state_payload.map(<[u8]>::to_vec),
                    successor.is_admission_ready(),
                ));
                true
            },
        ));

        assert_eq!(current_marking, net.initial_marking);
        assert_eq!(prepared.len(), 2);
        assert!(prepared.iter().all(|(_, _, _, _, ready)| *ready));
        for (_, fingerprint, packed, _, _) in &prepared {
            let packed = packed
                .as_ref()
                .expect("prepared Petri refs carry packed bytes");
            assert_eq!(*fingerprint, Some(fingerprint_marking(packed)));
        }

        let descriptor = PreparedSuccessorProvider::prepared_successor_batch_descriptor(&provider);
        descriptor
            .validate()
            .expect("prepared Petri successor descriptor should validate");
        let row = descriptor.render_evidence_row("MCC");
        PreparedSuccessorBatchDescriptor::validate_evidence_row(&row)
            .expect("rendered prepared successor descriptor should validate");
        assert!(row.contains("source_kind=mcc_petri"));
        assert!(row.contains("payload_witness=petri_marking_cas"));
        assert!(row.contains("admission_ready=true"));
        assert!(row.contains("successor_payload_kind=canonical_payload_only"));
        assert!(row.contains("default_consumers=mcc_petri"));
    }

    #[test]
    fn stopped_prepared_provider_restores_current_marking() {
        let net = branching_net();
        let setup = ExplorationSetup::analyze(&net);
        let por_strategy = PorStrategy::None;
        let mut provider = InterpretedSuccessorProvider::new(
            &net,
            &setup.marking_config,
            setup.pack_capacity,
            setup.num_transitions,
            None,
            &por_strategy,
            None,
        );
        let mut current_marking = net.initial_marking.clone();
        let completed = PreparedSuccessorProvider::for_each_prepared_successor(
            &mut provider,
            &mut current_marking,
            &mut |_successor| false,
        );

        assert!(!completed);
        assert_eq!(current_marking, net.initial_marking);
    }

    #[test]
    fn canonicalized_successors_do_not_mutate_parent_marking() {
        let net = symmetric_sink_net();
        let setup = ExplorationSetup::analyze(&net);
        let por_strategy = PorStrategy::None;
        let canonicalizer = super::super::symmetry::PetriCanonicalizer::build(&net);
        assert!(!canonicalizer.is_empty());
        let mut provider = InterpretedSuccessorProvider::new(
            &net,
            &setup.marking_config,
            setup.pack_capacity,
            setup.num_transitions,
            None,
            &por_strategy,
            Some(canonicalizer),
        );
        let mut current_marking = net.initial_marking.clone();
        let mut observed = Vec::new();

        let completed = provider.for_each_successor(&mut current_marking, &mut |successor| {
            observed.push((successor.transition, successor.marking.to_vec()));
            SuccessorVisit::Continue
        });

        assert!(completed);
        assert_eq!(current_marking, net.initial_marking);
        assert_eq!(
            observed,
            vec![
                (TransitionIdx(0), vec![0, 1, 1]),
                (TransitionIdx(1), vec![0, 1, 1]),
            ]
        );
    }
}
