// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Verification properties: default (auto-generated) and opt-in.

use serde::{Deserialize, Serialize};

use crate::model::{ObjectId, SyncId};

/// A property to verify on the concurrent model.
///
/// Default properties are generated automatically from the model structure.
/// Opt-in properties require `#[tla::check(...)]` annotations in Rust source.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "property")]
pub enum Property {
    // ── Default Properties (auto-generated) ──────────────────────
    /// No state where non-terminated processes have zero enabled transitions.
    /// `(∃ p ∈ Processes : pc[p] ∉ TerminalStates) ⇒ ENABLED(Next)`
    DeadlockFreedom,

    /// No cycle of any length in the wait-for graph (transitive closure).
    /// Successful try_lock held locks participate in the graph.
    LockOrderConsistency,

    /// Protection discipline: every access holds the correct guard in the
    /// correct mode. Write to RwLock-guarded data requires write guard.
    DataRaceFreedom,

    /// A specific process eventually terminates.
    Termination {
        /// ID of the process required to reach a terminal state.
        process: String,
    },

    /// Poison from a panicked lock holder is handled (not propagated).
    PoisonHandled {
        /// The mutex whose poison must be handled.
        mutex: SyncId,
    },

    /// Channel maintains FIFO order.
    ChannelFifo {
        /// The channel whose delivery order is checked.
        channel: SyncId,
    },

    /// Channel disconnect is handled (recv returns Err, not panic).
    ChannelDisconnect {
        /// The channel whose disconnect handling is checked.
        channel: SyncId,
    },

    /// All threads arrive at barrier in correct groups.
    BarrierCorrectness {
        /// The barrier whose grouping is checked.
        barrier: SyncId,
    },

    // ── Opt-in Properties (via #[tla::check(...)]) ───────────────
    /// All spawned threads are joined before main exits.
    /// Opt-in because detached threads are sometimes intentional.
    JoinCompleteness,

    /// No messages lost on channel disconnect.
    /// Opt-in because some protocols discard on disconnect.
    ChannelNoLoss {
        /// The channel whose messages must all be delivered.
        channel: SyncId,
    },

    /// Threads waiting on a condvar eventually make progress.
    /// Opt-in because programs may wait forever for environment input.
    CondvarProgress {
        /// The condvar whose waiters must eventually be woken.
        condvar: SyncId,
    },

    /// Writers to an RwLock eventually acquire the write lock.
    /// Opt-in because `std::sync::RwLock` doesn't guarantee writer fairness.
    RwLockWriterProgress {
        /// The rwlock whose pending writers must eventually acquire it.
        rwlock: SyncId,
    },

    /// A lock-free object is linearizable w.r.t. a sequential specification.
    /// Uses ObjectId (not SyncId) because lock-free structures are not sync
    /// primitives.
    Linearizable {
        /// The lock-free object being checked.
        object: ObjectId,
        /// Name of the sequential specification the object must refine.
        sequential_spec: String,
    },

    /// User-provided custom temporal formula.
    Custom {
        /// Identifier used to name the generated operator and report violations.
        name: String,
        /// The temporal formula in TLA+ syntax.
        formula: String,
    },
}

impl Property {
    /// Whether this property is generated by default or requires opt-in.
    #[must_use]
    pub fn is_default(&self) -> bool {
        matches!(
            self,
            Property::DeadlockFreedom
                | Property::LockOrderConsistency
                | Property::DataRaceFreedom
                | Property::Termination { .. }
                | Property::PoisonHandled { .. }
                | Property::ChannelFifo { .. }
                | Property::ChannelDisconnect { .. }
                | Property::BarrierCorrectness { .. }
        )
    }

    /// Whether this property is a safety property (invariant) vs liveness (temporal).
    #[must_use]
    pub fn is_safety(&self) -> bool {
        matches!(
            self,
            Property::DeadlockFreedom
                | Property::LockOrderConsistency
                | Property::DataRaceFreedom
                | Property::PoisonHandled { .. }
                | Property::ChannelFifo { .. }
                | Property::ChannelDisconnect { .. }
                | Property::BarrierCorrectness { .. }
                | Property::JoinCompleteness
                | Property::Linearizable { .. }
        )
    }
}
