// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0
//
// mcc-keyword-guard: allow-spaced-mention
// (this module emits no MCC stdout; comment present so a future spaced-
// literal regression test in #[cfg(test)] cannot be silently rewritten.)

//! Library backing for `ty-mcc-evidence-generate` and the equivalent
//! `ty-mccctl evidence-generate` subcommand.
//!
//! Emits the deterministic backend-evidence JSONL sidecar consumed by:
//! * `ty-mcc-smoke` (the BenchKit competition wrapper),
//! * `ty-mcc-backend-evidence-validate` (the canary validator),
//! * the freshness gate used by `mccctl doctor`.
//!
//! Replaces the former Python helper
//! invocation. All row content is generated by the
//! [`crate::mcc_backend_evidence_smoke`] library module so the binary,
//! unit tests, and any in-process callers share one source of truth.

use std::ffi::OsString;
use std::fs::{self, OpenOptions};
use std::io;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::Parser;

use crate::mcc_backend_evidence_smoke::{generated_replay_smoke_rows, write_jsonl};

/// Command-line arguments for the `ty-mcc-evidence-generate` helper.
#[derive(Parser, Debug)]
#[command(
    name = "ty-mcc-evidence-generate",
    about = "Generate a deterministic backend capability JSONL replay smoke artifact.",
    long_about = "Emits the MCC backend-evidence JSONL sidecar consumed by \
                  ty-mcc-smoke, ty-mcc-backend-evidence-validate, and the \
                  MCC doctor freshness gate. With no flags the generator \
                  writes JSONL to stdout."
)]
pub struct Cli {
    /// JSONL output path. Defaults to stdout when omitted (preserves the
    /// Python argparse default — `ty-mcc-smoke` shells out without
    /// `--output` and consumes stdout).
    #[arg(long, value_name = "PATH")]
    pub output: Option<PathBuf>,
}

/// Entry point used by the standalone `ty-mcc-evidence-generate` binary.
pub fn run() -> ExitCode {
    let cli = Cli::parse();
    execute(&cli)
}

/// Entry point used by `ty-mccctl evidence-generate` — parses an
/// explicit argv-style iterator so the parent CLI can construct it from
/// already-parsed clap state without re-shelling.
pub fn run_from<I, T>(args: I) -> ExitCode
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let cli = match Cli::try_parse_from(args) {
        Ok(cli) => cli,
        Err(err) => {
            // Clap's print prints help text to stdout for --help and
            // errors to stderr; preserve that behaviour.
            let _ = err.print();
            return ExitCode::from(u8::from(err.use_stderr()));
        }
    };
    execute(&cli)
}

fn execute(cli: &Cli) -> ExitCode {
    let rows = generated_replay_smoke_rows();
    match write_rows(&cli.output, &rows) {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("ty-mcc-evidence-generate: {err}");
            ExitCode::from(1)
        }
    }
}

fn write_rows(output: &Option<PathBuf>, rows: &[serde_json::Value]) -> io::Result<()> {
    match output {
        None => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            write_jsonl(rows, &mut handle)?;
        }
        Some(path) => {
            if let Some(parent) = path.parent() {
                if !parent.as_os_str().is_empty() {
                    fs::create_dir_all(parent)?;
                }
            }
            let mut handle = OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .open(path)?;
            write_jsonl(rows, &mut handle)?;
            // Mirror the Python "wrote N rows to PATH" log on stderr so
            // shell scripts that captured it still see the line — but
            // never on stdout, where the smoke wrapper expects only JSONL.
            eprintln!(
                "wrote {} backend evidence smoke row(s) to {}",
                rows.len(),
                path.display()
            );
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cli_parses_no_args_to_stdout_mode() {
        let cli = Cli::try_parse_from(["ty-mcc-evidence-generate"]).expect("ok");
        assert!(cli.output.is_none());
    }

    #[test]
    fn cli_accepts_output_flag() {
        let cli = Cli::try_parse_from(["ty-mcc-evidence-generate", "--output", "/tmp/jsonl"])
            .expect("ok");
        assert_eq!(
            cli.output.as_deref(),
            Some(std::path::Path::new("/tmp/jsonl"))
        );
    }

    #[test]
    fn write_rows_to_file_creates_jsonl() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("out.jsonl");
        let rows = generated_replay_smoke_rows();
        write_rows(&Some(path.clone()), &rows).expect("write");
        let text = fs::read_to_string(&path).expect("read");
        // Three smoke envelopes, each on its own JSONL line.
        assert_eq!(text.lines().count(), rows.len());
        for line in text.lines() {
            let _: serde_json::Value = serde_json::from_str(line).expect("each line is valid JSON");
        }
    }
}
