#!/usr/bin/env bash
# GPU-vs-CPU corpus sweep — proves the GPU lanes are (a) verdict-exact vs the
# CPU engines and (b) faster, across every GPU-accelerated MCC examination plus
# the TLA+ headline. Verdict-parity is the SOUNDNESS gate; wall time is the
# perf claim. Fail-closed by design means the *speedup set* is the specs the
# GPU admits — this sweep reports parity everywhere it runs and speedup where
# both arms complete.
#
# Usage: scripts/gpu_corpus_sweep.sh [ty-mcc-bin] [ty-bin] [out-dir]
# The A/B arms are pure env toggles (no engine change):
#   MCC  GPU: TY_MCC_GPU_STATESPACE_FORCE=1   CPU: TY_MCC_DISABLE_GPU_STATESPACE=1
#   TLA+ GPU: `ty check --gpu --force`          CPU: `ty check --no-gpu --force`
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TY_MCC="${1:-$REPO/target/release/ty-mcc}"
TY="${2:-$REPO/target/release/ty}"
OUT="${3:-$REPO/gpu_sweep_results}"
FIX="$REPO/tests/mcc_benchmarks"
DIJ="$HOME/tlaplus-examples/specifications/dijkstra-mutex"
TIMEOUT="${GPU_SWEEP_TIMEOUT:-180}"

mkdir -p "$OUT"
TSV="$OUT/results.tsv"
MD="$OUT/summary.md"
: >"$TSV"
printf 'frontend\tcase\texamination\tverdict_cpu\tverdict_gpu\tparity\twall_cpu_s\twall_gpu_s\tspeedup\n' >>"$TSV"

# MCC examinations to sweep. Non-property examinations run on every net; the
# formula examinations run only where the net ships the property XML.
ALWAYS="StateSpace ReachabilityDeadlock OneSafe StableMarking QuasiLiveness"
declare -A XML_EXAM=(
  [ReachabilityCardinality]=ReachabilityCardinality.xml
  [ReachabilityFireability]=ReachabilityFireability.xml
  [CTLCardinality]=CTLCardinality.xml
  [CTLFireability]=CTLFireability.xml
  [LTLCardinality]=LTLCardinality.xml
  [LTLFireability]=LTLFireability.xml
  [UpperBounds]=UpperBounds.xml
)

# Extract a stable verdict signature from ty-mcc stdout (verdicts/metric values,
# order-stable) so the two arms are comparable regardless of TECHNIQUES text.
verdict_sig() { grep -E '^(FORMULA|STATE_SPACE)' | awk '{print $2"="$3}' | sort | paste -sd';'; }

run_mcc() {  # $1=model dir  $2=exam  ->  echoes "verdict<TAB>wall_s"
  local dir="$1" exam="$2" env_arm="$3"
  local start end sig
  start="$(date +%s.%N)"
  sig="$(env $env_arm TY_MCC_DISABLE_MDD_STATESPACE=1 TY_MCC_DISABLE_TIER1_STATESPACE=1 \
        timeout "$TIMEOUT" "$TY_MCC" "$dir" --examination "$exam" --timeout "$TIMEOUT" 2>/dev/null | verdict_sig)"
  end="$(date +%s.%N)"
  printf '%s\t%.2f' "${sig:-NONE}" "$(echo "$end-$start" | bc)"
}

echo "== MCC sweep =="
for dir in "$FIX"/*/; do
  case_name="$(basename "$dir")"
  # applicable examinations = ALWAYS + any whose XML is present
  exams="$ALWAYS"
  for e in "${!XML_EXAM[@]}"; do
    [ -f "$dir/${XML_EXAM[$e]}" ] && exams="$exams $e"
  done
  for exam in $exams; do
    read -r vc wc < <(run_mcc "$dir" "$exam" "TY_MCC_DISABLE_GPU_STATESPACE=1")
    read -r vg wg < <(run_mcc "$dir" "$exam" "TY_MCC_GPU_STATESPACE_FORCE=1")
    parity=MISMATCH; [ "$vc" = "$vg" ] && parity=MATCH
    sp="-"; if [ "$vc" = "$vg" ] && [ "$(echo "$wg > 0" | bc)" = 1 ]; then sp="$(echo "scale=2; $wc/$wg" | bc)"; fi
    printf 'MCC\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$case_name" "$exam" "$vc" "$vg" "$parity" "$wc" "$wg" "$sp" >>"$TSV"
    printf '  %-18s %-24s %s (cpu %ss / gpu %ss, x%s)\n' "$case_name" "$exam" "$parity" "$wc" "$wg" "$sp"
  done
done

echo "== TLA+ sweep (dijkstra headline; GPU explores the RAW space, CPU the symmetry-reduced space) =="
if [ -d "$DIJ" ]; then
  for spec in MCDijkstra3 MCDijkstra4; do
    [ -f "$DIJ/$spec.tla" ] || continue
    cs="$(date +%s.%N)"; vc="$(cd "$DIJ" && timeout "$TIMEOUT" "$TY" check "$spec.tla" --no-gpu --force 2>/dev/null | grep -oE 'States found: [0-9]+' | grep -oE '[0-9]+')"; ce="$(date +%s.%N)"
    gs="$(date +%s.%N)"; vg="$(cd "$DIJ" && timeout "$TIMEOUT" "$TY" check "$spec.tla" --gpu --force 2>/dev/null | grep -oE 'States found: [0-9]+' | grep -oE '[0-9]+')"; ge="$(date +%s.%N)"
    wc="$(echo "$ce-$cs"|bc)"; wg="$(echo "$ge-$gs"|bc)"
    printf 'TLA+\t%s\tSafety\t%s\t%s\tRAW-vs-REDUCED\t%.2f\t%.2f\t-\n' "$spec" "${vc:-NONE}" "${vg:-NONE}" "$wc" "$wg" >>"$TSV"
    printf '  %-12s cpu=%s states (%ss)  gpu=%s states raw (%ss)\n' "$spec" "${vc:-?}" "$wc" "${vg:-?}" "$wg"
  done
fi

# ---- markdown summary ----
{
  echo "# GPU-vs-CPU corpus sweep"
  echo
  echo "Generated by \`scripts/gpu_corpus_sweep.sh\`. Verdict-parity is the soundness gate; speedup is the perf claim."
  echo
  echo "## MCC (verdict-exact + timed, per examination)"
  echo
  echo "| case | examination | parity | cpu (s) | gpu (s) | speedup |"
  echo "|---|---|---|---:|---:|---:|"
  awk -F'\t' 'NR>1 && $1=="MCC"{printf "| %s | %s | %s | %s | %s | %s |\n",$2,$3,$6,$7,$8,$9}' "$TSV"
  echo
  mcc_total=$(awk -F'\t' 'NR>1 && $1=="MCC"' "$TSV" | wc -l)
  mcc_match=$(awk -F'\t' 'NR>1 && $1=="MCC" && $6=="MATCH"' "$TSV" | wc -l)
  echo "**MCC verdict parity: $mcc_match / $mcc_total MATCH.**"
  echo
  echo "## TLA+ (dijkstra headline)"
  echo
  echo "| spec | cpu states (reduced) | cpu (s) | gpu states (raw) | gpu (s) |"
  echo "|---|---:|---:|---:|---:|"
  awk -F'\t' 'NR>1 && $1=="TLA+"{printf "| %s | %s | %s | %s | %s |\n",$2,$4,$7,$5,$8}' "$TSV"
} >"$MD"

echo
echo "Wrote $TSV and $MD"
mcc_total=$(awk -F'\t' 'NR>1 && $1=="MCC"' "$TSV" | wc -l)
mcc_match=$(awk -F'\t' 'NR>1 && $1=="MCC" && $6=="MATCH"' "$TSV" | wc -l)
echo "MCC verdict parity: $mcc_match / $mcc_total MATCH"
[ "$mcc_match" = "$mcc_total" ] && exit 0 || exit 1
