// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Per-action branching metrics for CDEMC.
//!
//! Contains the `ActionMetrics` struct used by BFS and the oracle to make
//! routing decisions.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

/// Per-action branching metrics for oracle routing decisions.
///
/// Populated by BFS during exploration, read by the oracle to identify
/// high-branching actions suitable for symbolic handling.
pub(crate) struct ActionMetrics {
    /// Total successor states generated by this action across all firings.
    pub(crate) total_successors: AtomicU64,
    /// Number of times this action was evaluated (fired from any state).
    pub(crate) times_evaluated: AtomicU64,
    /// Whether this action's expressions are within the SMT-compatible fragment.
    /// Set once at startup based on static analysis; never changes at runtime.
    pub(crate) smt_compatible: AtomicBool,
    /// Whether this action has a compiled/native implementation available.
    ///
    /// Set by the model checker after successful JIT compilation of the
    /// action's next-state relation. Compiled actions usually execute faster
    /// in BFS and should be preferred for `BfsOnly` routing by the oracle.
    ///
    /// Part of #3854.
    pub(crate) jit_compiled: AtomicBool,
}

impl ActionMetrics {
    /// Record that this action produced `successor_count` successors from one
    /// firing. Thread-safe: uses relaxed atomics (advisory metrics, not
    /// correctness-critical).
    ///
    /// Part of #3784.
    #[inline]
    pub(crate) fn record_firing(&self, successor_count: u64) {
        self.times_evaluated.fetch_add(1, Ordering::Relaxed);
        self.total_successors
            .fetch_add(successor_count, Ordering::Relaxed);
    }
}
