// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! STATEMENT PINS — closing the statement-translation trust residual for the clean-kernel
//! soundness proofs (`proofs/clean/*.clean`, kernel-checked by `clean_soundness_proofs.rs`).
//!
//! ## The residual this closes
//!
//! The clean CIC kernel verifies each proof against the ELABORATED statement. If clean's
//! ELABORATOR mistranslated the surface statement (wrong binder structure, wrong de Bruijn
//! index, wrong universe level, wrong constant), the kernel would faithfully check the WRONG
//! proposition — a false trust label the kernel itself cannot catch. This test removes the
//! elaborator from that loop for the pinned statements: each pin is the kernel `Expr` of the
//! SURFACE statement, HAND-BUILT from raw constructors (`Expr::pi` / `Expr::app` /
//! `Expr::bvar` / `Expr::const_` / `Expr::sort` — **no parser, no elaborator, anywhere in pin
//! construction**), and asserted **definitionally equal** (`TypeChecker::is_def_eq`, the
//! kernel's own judgment) to the type the elaborator registered. The proof files are parsed +
//! elaborated ONLY to obtain the registered constants — the registered type is the object
//! under test, never an input to a pin.
//!
//! ## What the pins remove from the TCB
//!
//!   - clean-elaborator statement translation for every pinned theorem: binder order and
//!     count, de Bruijn structure, universe levels (`Eq.{1}`, `List.{0}`, `Prod.{0,0}`,
//!     `ite.{1}`), and every constant reference in the statement.
//!   - the `Reach` inductive's SHAPE in each file that declares it: the type former AND both
//!     constructor types (`Reach`, `Reach.base`, `Reach.step`) are pinned, so the reachability
//!     predicate quantified over by `reach_least` / `d3_step_simulation` /
//!     `refinement_safety_transfer` / `refinement_transitivity` means base-or-step exactly.
//!     (The recursor is generated by the KERNEL from these, not by the elaborator.)
//!   - `SetMaskSound.mem`'s defining BODY (`fun (m i : Nat) => Nat.testBit m i`): pinned as a
//!     VALUE pin, so `mask_injective`'s statement bottoms out in the prelude's `Nat.testBit`
//!     with no file-local elaborated definition left in its trust chain.
//!
//! ## What REMAINS elaborator-translated (honest residual)
//!
//!   - Bodies of the other referenced file-local DEFS. A pinned statement that cites such a
//!     def is pinned only DOWN TO that def's name; its body is still elaborator-trusted:
//!     `PackInj.{AllLt, baseValue}`, `MixedRadixInj.{DigitsLt, mrEnc}`,
//!     `L1Cover.{AllLt, baseValue}`, `L1bMixed.{AllDigitLt, mixedRadix, radProduct}`,
//!     `LexLive.lexLt`, `ColCard.rangeList`, `TupleCount.{allTuples, prod}`, and R1's
//!     `memberOf` / `listExistsBeq`. (Each has `rfl` reduction-sanity theorems in its file,
//!     which constrain — but do not fully pin — the elaborated body.)
//!   - The PRELUDE constants the statements cite (`Eq`, `And`, `Or`, `Iff`, `False`, `Nat.*`,
//!     `List.length`, `Prod`, `Bool.*`, `ite`, `instDecidableEqBool`): their definitions come
//!     from `Environment::with_prelude()`, part of clean's kernel trust anchor — not per-file
//!     elaboration, but trusted nonetheless.
//!   - K2's `if c then a else b` SUGAR: the pin fixes the standard desugaring
//!     `@ite.{1} Nat (c = Bool.true) (instDecidableEqBool c Bool.true) a b` — i.e. the
//!     Decidable-instance form is part of the pinned statement (any change to the desugaring
//!     fails the pin loudly, which is the point).
//!   - `is_def_eq` itself is kernel code: a pin certifies the registered type is
//!     DEFINITIONALLY the hand-built statement, on the kernel's judgment.
//!
//! ## Negative controls
//!
//! Three deliberately WRONG pins prove the comparison can fail: a `reach_least` pin whose
//! conclusion is `Init s` instead of `R s`; a `reach_least` pin with `hstep`'s hypotheses
//! swapped; and a correct `mask_injective` pin compared against a DIFFERENT theorem's type.

use std::collections::BTreeMap;
use std::path::PathBuf;

use clean_elab::{elaborate_decl_and_register, preprocess_decl_with_context, FileContext};
use clean_kernel::env::Environment;
use clean_kernel::{BinderInfo, Expr, Level, Name, TypeChecker};
use clean_parser::parse_file;

// ═══════════════════════════════════════════════════════════════════════════════════════════
// Raw-constructor helpers. NOTHING here touches clean's parser or elaborator: only the kernel
// Expr constructors. `v(i)` is de Bruijn (0 = innermost binder); every binder is explicit
// (`BinderInfo::Default`), matching how clean registers parenthesized surface binders.
// ═══════════════════════════════════════════════════════════════════════════════════════════

fn v(i: u32) -> Expr {
    Expr::bvar(i)
}
fn pi(ty: Expr, body: Expr) -> Expr {
    Expr::pi(BinderInfo::Default, ty, body)
}
fn lam(ty: Expr, body: Expr) -> Expr {
    Expr::lam(BinderInfo::Default, ty, body)
}
/// Non-dependent arrow `a -> b` (still a Pi; the codomain must be indexed as if under one
/// extra anonymous binder).
fn arr(a: Expr, b: Expr) -> Expr {
    Expr::arrow(a, b)
}
fn app(f: Expr, x: Expr) -> Expr {
    Expr::app(f, x)
}
fn apps<const N: usize>(f: Expr, args: [Expr; N]) -> Expr {
    Expr::apps(f, args)
}
/// Constant with NO universe levels (level-monomorphic).
fn cn(name: &str) -> Expr {
    Expr::const_str(name)
}
/// Constant with explicit universe levels.
fn cl(name: &str, levels: Vec<Level>) -> Expr {
    Expr::const_str_levels(name, levels)
}
fn l0() -> Level {
    Level::zero()
}
fn l1() -> Level {
    Level::succ(Level::zero())
}
fn prop() -> Expr {
    Expr::prop()
}
/// `Type` (= Sort 1), the universe of the quantified state spaces.
fn type0() -> Expr {
    Expr::type_()
}
fn nat() -> Expr {
    cn("Nat")
}
fn bool_() -> Expr {
    cn("Bool")
}
fn false_() -> Expr {
    cn("False")
}
/// `List.{0} t` — the statements only ever instantiate `List` at `Type 0` elements.
fn list0(t: Expr) -> Expr {
    app(cl("List", vec![l0()]), t)
}
fn list_nat() -> Expr {
    list0(nat())
}
/// `Prod.{0,0} Nat Nat` — the lexicographic measure's pair type.
fn prod_nn() -> Expr {
    apps(cl("Prod", vec![l0(), l0()]), [nat(), nat()])
}
/// `@Eq.{1} t a b` — every statement equality is at a `Type 0` carrier (Nat / Bool / List Nat
/// / a quantified `State : Type`), i.e. `Sort 1`, so the level is always `1`.
fn eq1(t: Expr, a: Expr, b: Expr) -> Expr {
    apps(cl("Eq", vec![l1()]), [t, a, b])
}
fn and(a: Expr, b: Expr) -> Expr {
    apps(cn("And"), [a, b])
}
fn or(a: Expr, b: Expr) -> Expr {
    apps(cn("Or"), [a, b])
}
fn iff(a: Expr, b: Expr) -> Expr {
    apps(cn("Iff"), [a, b])
}
fn nat_lt(a: Expr, b: Expr) -> Expr {
    apps(cn("Nat.lt"), [a, b])
}
/// `@List.length.{0} t l`.
fn len0(t: Expr, l: Expr) -> Expr {
    apps(cl("List.length", vec![l0()]), [t, l])
}

// ═══════════════════════════════════════════════════════════════════════════════════════════
// PIN BUILDERS — one per pinned statement. Each carries the intended surface statement as a
// comment; the raw Expr below it IS the pin (hand-transcribed, de Bruijn indices computed by
// hand from the binder telescope).
// ═══════════════════════════════════════════════════════════════════════════════════════════

/// The `Reach` inductive's TYPE FORMER (declared identically in tB / d3 / d3b / d3c):
///
/// ```text
/// Reach : (State : Type) -> (State -> Prop) -> (State -> State -> Prop) -> State -> Prop
/// ```
fn pin_reach_type() -> Expr {
    pi(
        type0(), // State
        arr(
            arr(v(0), prop()), // Init : State -> Prop
            arr(
                arr(v(1), arr(v(2), prop())), // Next : State -> State -> Prop
                arr(v(2), prop()),            // State -> Prop
            ),
        ),
    )
}

/// ```text
/// Reach.base : (State : Type) -> (Init : State -> Prop) -> (Next : State -> State -> Prop)
///           -> (s : State) -> Init s -> Reach State Init Next s
/// ```
fn pin_reach_base() -> Expr {
    pi(
        type0(), // State
        pi(
            arr(v(0), prop()), // Init
            pi(
                arr(v(1), arr(v(2), prop())), // Next
                pi(
                    v(2), // s : State
                    arr(
                        app(v(2), v(0)), // Init s
                        // under the anonymous binder: State@4 Init@3 Next@2 s@1
                        apps(cn("Reach"), [v(4), v(3), v(2), v(1)]),
                    ),
                ),
            ),
        ),
    )
}

/// ```text
/// Reach.step : (State : Type) -> (Init : State -> Prop) -> (Next : State -> State -> Prop)
///           -> (s t : State) -> Reach State Init Next s -> Next s t
///           -> Reach State Init Next t
/// ```
fn pin_reach_step() -> Expr {
    pi(
        type0(),
        pi(
            arr(v(0), prop()),
            pi(
                arr(v(1), arr(v(2), prop())),
                pi(
                    v(2), // s
                    pi(
                        v(3), // t   (State@3 with s in scope)
                        arr(
                            // Reach State Init Next s : t@0 s@1 Next@2 Init@3 State@4
                            apps(cn("Reach"), [v(4), v(3), v(2), v(1)]),
                            arr(
                                // Next s t : (+1 anon) Next@3 s@2 t@1
                                apps(v(3), [v(2), v(1)]),
                                // Reach State Init Next t : (+2 anons) State@6 Init@5 Next@4 t@2
                                apps(cn("Reach"), [v(6), v(5), v(4), v(2)]),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// FLAGSHIP 1 — `reach_least` (tB_reachable_mem_R.clean), the inductive-invariant safety
/// principle:
///
/// ```text
/// (State : Type) -> (Init : State -> Prop) -> (Next : State -> State -> Prop)
/// -> (R : State -> Prop)
/// -> (hinit : (s : State) -> Init s -> R s)
/// -> (hstep : (s t : State) -> R s -> Next s t -> R t)
/// -> (s : State) -> Reach State Init Next s -> R s
/// ```
fn pin_reach_least() -> Expr {
    pi(
        type0(), // State
        pi(
            arr(v(0), prop()), // Init
            pi(
                arr(v(1), arr(v(2), prop())), // Next
                pi(
                    arr(v(2), prop()), // R
                    pi(
                        // hinit : (s : State@3) -> Init s -> R s
                        pi(v(3), arr(app(v(3), v(0)), app(v(2), v(1)))),
                        pi(
                            // hstep : (s : State@4) -> (t : State@5) -> R s -> Next s t -> R t
                            pi(
                                v(4),
                                pi(
                                    v(5),
                                    arr(
                                        app(v(3), v(1)), // R s
                                        arr(
                                            apps(v(5), [v(2), v(1)]), // Next s t
                                            app(v(5), v(2)),          // R t
                                        ),
                                    ),
                                ),
                            ),
                            pi(
                                v(5), // s : State
                                arr(
                                    // Reach State Init Next s : s@0 hstep@1 hinit@2 R@3 Next@4 Init@5 State@6
                                    apps(cn("Reach"), [v(6), v(5), v(4), v(0)]),
                                    // R s : (+1 anon) R@4 s@1
                                    app(v(4), v(1)),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// FLAGSHIP 2 — `PackInj.pack_injective` (S1_pack_injective.clean), base-b encoder
/// injectivity:
///
/// ```text
/// (b : Nat) -> (xs ys : List Nat) -> AllLt b xs -> AllLt b ys
/// -> @Eq Nat (@List.length Nat xs) (@List.length Nat ys)
/// -> @Eq Nat (baseValue b xs) (baseValue b ys)
/// -> @Eq (List Nat) xs ys
/// ```
fn pin_pack_injective() -> Expr {
    pi(
        nat(), // b
        pi(
            list_nat(), // xs
            pi(
                list_nat(), // ys
                pi(
                    apps(cn("PackInj.AllLt"), [v(2), v(1)]), // AllLt b xs
                    pi(
                        apps(cn("PackInj.AllLt"), [v(3), v(1)]), // AllLt b ys
                        pi(
                            // length xs = length ys : hy@0 hx@1 ys@2 xs@3 b@4
                            eq1(nat(), len0(nat(), v(3)), len0(nat(), v(2))),
                            pi(
                                // baseValue b xs = baseValue b ys : hlen@0 … ys@3 xs@4 b@5
                                eq1(
                                    nat(),
                                    apps(cn("PackInj.baseValue"), [v(5), v(4)]),
                                    apps(cn("PackInj.baseValue"), [v(5), v(3)]),
                                ),
                                // xs = ys : hval@0 hlen@1 hy@2 hx@3 ys@4 xs@5
                                eq1(list_nat(), v(5), v(4)),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// FLAGSHIP 3 — `MixedRadixInj.mixed_radix_injective` (S1b_mixed_radix_injective.clean),
/// mixed-radix (per-column radix) encoder injectivity:
///
/// ```text
/// (rs ds1 ds2 : List Nat) -> DigitsLt rs ds1 -> DigitsLt rs ds2
/// -> @Eq Nat (mrEnc rs ds1) (mrEnc rs ds2) -> @Eq (List Nat) ds1 ds2
/// ```
fn pin_mixed_radix_injective() -> Expr {
    pi(
        list_nat(), // rs
        pi(
            list_nat(), // ds1
            pi(
                list_nat(), // ds2
                pi(
                    apps(cn("MixedRadixInj.DigitsLt"), [v(2), v(1)]), // DigitsLt rs ds1
                    pi(
                        apps(cn("MixedRadixInj.DigitsLt"), [v(3), v(1)]), // DigitsLt rs ds2
                        pi(
                            // mrEnc rs ds1 = mrEnc rs ds2 : h2@0 h1@1 ds2@2 ds1@3 rs@4
                            eq1(
                                nat(),
                                apps(cn("MixedRadixInj.mrEnc"), [v(4), v(3)]),
                                apps(cn("MixedRadixInj.mrEnc"), [v(4), v(2)]),
                            ),
                            // ds1 = ds2 : hv@0 h2@1 h1@2 ds2@3 ds1@4
                            eq1(list_nat(), v(4), v(3)),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// FLAGSHIP 4 — `SetMaskSound.mask_injective` (M1_setmask_soundness.clean), bitmask-encoder
/// injectivity (bit-extensionality on the membership model):
///
/// ```text
/// (a b : Nat) -> ((i : Nat) -> @Eq Bool (mem a i) (mem b i)) -> @Eq Nat a b
/// ```
fn pin_mask_injective() -> Expr {
    pi(
        nat(), // a
        pi(
            nat(), // b
            pi(
                // (i : Nat) -> mem a i = mem b i    (a@2 b@1 with i bound)
                pi(
                    nat(),
                    eq1(
                        bool_(),
                        apps(cn("SetMaskSound.mem"), [v(2), v(0)]),
                        apps(cn("SetMaskSound.mem"), [v(1), v(0)]),
                    ),
                ),
                // a = b : h@0 b@1 a@2
                eq1(nat(), v(2), v(1)),
            ),
        ),
    )
}

/// `SetMaskSound.mem`'s TYPE: `Nat -> Nat -> Bool`.
fn pin_mem_type() -> Expr {
    arr(nat(), arr(nat(), bool_()))
}

/// `SetMaskSound.mem`'s defining VALUE: `fun (m i : Nat) => Nat.testBit m i`. Pinning the body
/// removes the last file-local elaborated definition from `mask_injective`'s trust chain.
fn pin_mem_value() -> Expr {
    lam(nat(), lam(nat(), apps(cn("Nat.testBit"), [v(1), v(0)])))
}

/// FLAGSHIP 5 — `d4_no_infinite_descent` (d4_no_infinite_descent.clean), the liveness
/// (well-founded measure) core — no infinite strictly-decreasing Nat sequence:
///
/// ```text
/// (f : Nat -> Nat) -> ((n : Nat) -> Nat.lt (f (Nat.succ n)) (f n)) -> False
/// ```
fn pin_d4_no_infinite_descent() -> Expr {
    pi(
        arr(nat(), nat()), // f
        pi(
            // (n : Nat) -> f (n+1) < f n    (f@1 with n bound)
            pi(
                nat(),
                nat_lt(app(v(1), app(cn("Nat.succ"), v(0))), app(v(1), v(0))),
            ),
            false_(),
        ),
    )
}

/// FLAGSHIP 6 — `d3_step_simulation` (d3_step_simulation.clean), refinement-verdict
/// soundness — step-simulation implies reachability inclusion:
///
/// ```text
/// (C A : Type) -> (InitC : C -> Prop) -> (InitA : A -> Prop)
/// -> (StepC : C -> C -> Prop) -> (StepA : A -> A -> Prop) -> (f : C -> A)
/// -> (hInit : (c : C) -> InitC c -> InitA (f c))
/// -> (hSim : (c c' : C) -> StepC c c' -> Or (StepA (f c) (f c')) (@Eq A (f c) (f c')))
/// -> (c : C) -> Reach C InitC StepC c -> Reach A InitA StepA (f c)
/// ```
fn pin_d3_step_simulation() -> Expr {
    pi(
        type0(), // C
        pi(
            type0(), // A
            pi(
                arr(v(1), prop()), // InitC : C -> Prop
                pi(
                    arr(v(1), prop()), // InitA : A -> Prop
                    pi(
                        arr(v(3), arr(v(4), prop())), // StepC : C -> C -> Prop
                        pi(
                            arr(v(3), arr(v(4), prop())), // StepA : A -> A -> Prop
                            pi(
                                arr(v(5), v(5)), // f : C -> A
                                pi(
                                    // hInit : (c : C@6) -> InitC c -> InitA (f c)
                                    pi(v(6), arr(app(v(5), v(0)), app(v(5), app(v(2), v(1))))),
                                    pi(
                                        // hSim : (c : C@7) -> (c' : C@8)
                                        //     -> StepC c c'
                                        //     -> Or (StepA (f c) (f c')) (Eq A (f c) (f c'))
                                        pi(
                                            v(7),
                                            pi(
                                                v(8),
                                                arr(
                                                    apps(v(5), [v(1), v(0)]), // StepC c c'
                                                    or(
                                                        apps(
                                                            v(5), // StepA
                                                            [app(v(4), v(2)), app(v(4), v(1))],
                                                        ),
                                                        eq1(
                                                            v(9), // A
                                                            app(v(4), v(2)),
                                                            app(v(4), v(1)),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        pi(
                                            v(8), // c : C
                                            arr(
                                                // Reach C InitC StepC c
                                                apps(cn("Reach"), [v(9), v(7), v(5), v(0)]),
                                                // Reach A InitA StepA (f c)
                                                apps(
                                                    cn("Reach"),
                                                    [v(9), v(7), v(5), app(v(4), v(1))],
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// STRETCH — `refinement_safety_transfer` (d3b_refinement_safety_transfer.clean): an abstract
/// inductive invariant pulls back along a step-simulation to all concrete-reachable states:
///
/// ```text
/// (C A : Type) -> (InitC : C -> Prop) -> (InitA : A -> Prop)
/// -> (StepC : C -> C -> Prop) -> (StepA : A -> A -> Prop) -> (f : C -> A)
/// -> (hInit : (c : C) -> InitC c -> InitA (f c))
/// -> (hSim : (c c' : C) -> StepC c c' -> Or (StepA (f c) (f c')) (@Eq A (f c) (f c')))
/// -> (J : A -> Prop)
/// -> (hJinit : (a : A) -> InitA a -> J a)
/// -> (hJstep : (a a' : A) -> J a -> StepA a a' -> J a')
/// -> (c : C) -> Reach C InitC StepC c -> J (f c)
/// ```
fn pin_refinement_safety_transfer() -> Expr {
    pi(
        type0(),
        pi(
            type0(),
            pi(
                arr(v(1), prop()),
                pi(
                    arr(v(1), prop()),
                    pi(
                        arr(v(3), arr(v(4), prop())),
                        pi(
                            arr(v(3), arr(v(4), prop())),
                            pi(
                                arr(v(5), v(5)),
                                pi(
                                    pi(v(6), arr(app(v(5), v(0)), app(v(5), app(v(2), v(1))))),
                                    pi(
                                        pi(
                                            v(7),
                                            pi(
                                                v(8),
                                                arr(
                                                    apps(v(5), [v(1), v(0)]),
                                                    or(
                                                        apps(
                                                            v(5),
                                                            [app(v(4), v(2)), app(v(4), v(1))],
                                                        ),
                                                        eq1(v(9), app(v(4), v(2)), app(v(4), v(1))),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        pi(
                                            arr(v(7), prop()), // J : A -> Prop (A@7)
                                            pi(
                                                // hJinit : (a : A@8) -> InitA a -> J a
                                                pi(v(8), arr(app(v(7), v(0)), app(v(2), v(1)))),
                                                pi(
                                                    // hJstep : (a : A@9) -> (a' : A@10)
                                                    //       -> J a -> StepA a a' -> J a'
                                                    pi(
                                                        v(9),
                                                        pi(
                                                            v(10),
                                                            arr(
                                                                app(v(3), v(1)), // J a
                                                                arr(
                                                                    apps(v(8), [v(2), v(1)]),
                                                                    app(v(5), v(2)), // J a'
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                    pi(
                                                        v(11), // c : C
                                                        arr(
                                                            apps(
                                                                cn("Reach"),
                                                                [v(12), v(10), v(8), v(0)],
                                                            ),
                                                            // J (f c)
                                                            app(v(4), app(v(7), v(1))),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// STRETCH — `refinement_transitivity` (d3c_refinement_transitivity.clean): composing two
/// step-simulations transfers reachability C -> B through `g ∘ f`:
///
/// ```text
/// (C A B : Type)
/// -> (InitC : C -> Prop) -> (InitA : A -> Prop) -> (InitB : B -> Prop)
/// -> (StepC : C -> C -> Prop) -> (StepA : A -> A -> Prop) -> (StepB : B -> B -> Prop)
/// -> (f : C -> A) -> (g : A -> B)
/// -> (hInitF : (c : C) -> InitC c -> InitA (f c))
/// -> (hSimF : (c c' : C) -> StepC c c' -> Or (StepA (f c) (f c')) (@Eq A (f c) (f c')))
/// -> (hInitG : (a : A) -> InitA a -> InitB (g a))
/// -> (hSimG : (a a' : A) -> StepA a a' -> Or (StepB (g a) (g a')) (@Eq B (g a) (g a')))
/// -> (c : C) -> Reach C InitC StepC c -> Reach B InitB StepB (g (f c))
/// ```
fn pin_refinement_transitivity() -> Expr {
    pi(
        type0(),
        pi(
            type0(),
            pi(
                type0(),
                pi(
                    arr(v(2), prop()), // InitC (C@2)
                    pi(
                        arr(v(2), prop()), // InitA (A@2)
                        pi(
                            arr(v(2), prop()), // InitB (B@2)
                            pi(
                                arr(v(5), arr(v(6), prop())), // StepC (C@5)
                                pi(
                                    arr(v(5), arr(v(6), prop())), // StepA (A@5)
                                    pi(
                                        arr(v(5), arr(v(6), prop())), // StepB (B@5)
                                        pi(
                                            arr(v(8), v(8)), // f : C -> A
                                            pi(
                                                arr(v(8), v(8)), // g : A -> B
                                                pi(
                                                    // hInitF : (c : C@10) -> InitC c -> InitA (f c)
                                                    pi(
                                                        v(10),
                                                        arr(
                                                            app(v(8), v(0)),
                                                            app(v(8), app(v(3), v(1))),
                                                        ),
                                                    ),
                                                    pi(
                                                        // hSimF : (c : C@11) -> (c' : C@12)
                                                        //  -> StepC c c'
                                                        //  -> Or (StepA (f c) (f c'))
                                                        //        (Eq A (f c) (f c'))
                                                        pi(
                                                            v(11),
                                                            pi(
                                                                v(12),
                                                                arr(
                                                                    apps(v(7), [v(1), v(0)]),
                                                                    or(
                                                                        apps(
                                                                            v(7),
                                                                            [
                                                                                app(v(5), v(2)),
                                                                                app(v(5), v(1)),
                                                                            ],
                                                                        ),
                                                                        eq1(
                                                                            v(13),
                                                                            app(v(5), v(2)),
                                                                            app(v(5), v(1)),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                        pi(
                                                            // hInitG : (a : A@11)
                                                            //  -> InitA a -> InitB (g a)
                                                            pi(
                                                                v(11),
                                                                arr(
                                                                    app(v(9), v(0)),
                                                                    app(v(9), app(v(4), v(1))),
                                                                ),
                                                            ),
                                                            pi(
                                                                // hSimG : (a : A@12) -> (a' : A@13)
                                                                //  -> StepA a a'
                                                                //  -> Or (StepB (g a) (g a'))
                                                                //        (Eq B (g a) (g a'))
                                                                pi(
                                                                    v(12),
                                                                    pi(
                                                                        v(13),
                                                                        arr(
                                                                            apps(
                                                                                v(8),
                                                                                [v(1), v(0)],
                                                                            ),
                                                                            or(
                                                                                apps(
                                                                                    v(8),
                                                                                    [
                                                                                        app(
                                                                                            v(6),
                                                                                            v(2),
                                                                                        ),
                                                                                        app(
                                                                                            v(6),
                                                                                            v(1),
                                                                                        ),
                                                                                    ],
                                                                                ),
                                                                                eq1(
                                                                                    v(14),
                                                                                    app(v(6), v(2)),
                                                                                    app(v(6), v(1)),
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                                pi(
                                                                    v(14), // c : C
                                                                    arr(
                                                                        apps(
                                                                            cn("Reach"),
                                                                            [
                                                                                v(15),
                                                                                v(12),
                                                                                v(9),
                                                                                v(0),
                                                                            ],
                                                                        ),
                                                                        // Reach B InitB StepB (g (f c))
                                                                        apps(
                                                                            cn("Reach"),
                                                                            [
                                                                                v(14),
                                                                                v(11),
                                                                                v(8),
                                                                                app(
                                                                                    v(6),
                                                                                    app(v(7), v(1)),
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// STRETCH — `LexLive.no_infinite_lex_descent` (d4b_lex_liveness.clean): no run's (Nat,Nat)
/// lexicographic measure strictly lex-decreases forever:
///
/// ```text
/// (f : Nat -> Prod Nat Nat) -> ((n : Nat) -> lexLt (f (Nat.succ n)) (f n)) -> False
/// ```
fn pin_no_infinite_lex_descent() -> Expr {
    pi(
        arr(nat(), prod_nn()), // f
        pi(
            pi(
                nat(),
                apps(
                    cn("LexLive.lexLt"),
                    [app(v(1), app(cn("Nat.succ"), v(0))), app(v(1), v(0))],
                ),
            ),
            false_(),
        ),
    )
}

/// STRETCH — `L1bMixed.mixed_radix_coverage` (L1b_mixed_radix_coverage.clean): every
/// in-range mixed-radix digit tuple encodes strictly below the radix product:
///
/// ```text
/// (l : List (Prod Nat Nat)) -> AllDigitLt l -> Nat.lt (mixedRadix l) (radProduct l)
/// ```
fn pin_mixed_radix_coverage() -> Expr {
    pi(
        list0(prod_nn()), // l
        pi(
            app(cn("L1bMixed.AllDigitLt"), v(0)),
            nat_lt(
                app(cn("L1bMixed.mixedRadix"), v(1)),
                app(cn("L1bMixed.radProduct"), v(1)),
            ),
        ),
    )
}

/// STRETCH — `L1Cover.baseValue_lt_pow` (L1_domain_covers.clean): a bounded digit list's
/// base-b value lies strictly below b^length — the encoder stays inside its domain:
///
/// ```text
/// (b : Nat) -> (l : List Nat) -> Nat.le (Nat.succ Nat.zero) b -> AllLt b l
/// -> Nat.lt (baseValue b l) (Nat.pow b (List.length l))
/// ```
fn pin_base_value_lt_pow() -> Expr {
    pi(
        nat(), // b
        pi(
            list_nat(), // l
            pi(
                apps(cn("Nat.le"), [app(cn("Nat.succ"), cn("Nat.zero")), v(1)]), // 1 <= b
                pi(
                    apps(cn("L1Cover.AllLt"), [v(2), v(1)]),
                    nat_lt(
                        apps(cn("L1Cover.baseValue"), [v(3), v(2)]),
                        apps(cn("Nat.pow"), [v(3), len0(nat(), v(2))]),
                    ),
                ),
            ),
        ),
    )
}

/// STRETCH — `R1_general_membership` (R1_general_membership.clean): the Bool membership fold
/// agrees with the propositional existence predicate:
///
/// ```text
/// (x : Nat) -> (l : List Nat) -> Iff (@Eq Bool (memberOf x l) Bool.true) (listExistsBeq x l)
/// ```
fn pin_r1_general_membership() -> Expr {
    pi(
        nat(),
        pi(
            list_nat(),
            iff(
                eq1(bool_(), apps(cn("memberOf"), [v(1), v(0)]), cn("Bool.true")),
                apps(cn("listExistsBeq"), [v(1), v(0)]),
            ),
        ),
    )
}

/// STRETCH — `K2_ite_disjunctive` (K2_ite_disjunctive.clean): an IF-update equals its
/// disjunctive expansion:
///
/// ```text
/// (c : Bool) -> (a b v : Nat)
/// -> Iff (@Eq Nat v (if c then a else b))
///        (Or (And (@Eq Bool c true) (@Eq Nat v a)) (And (@Eq Bool c false) (@Eq Nat v b)))
/// ```
///
/// The `if c then a else b` sugar is pinned as its standard desugaring
/// `@ite.{1} Nat (@Eq Bool c Bool.true) (instDecidableEqBool c Bool.true) a b` — the
/// Decidable-instance form is part of the pinned statement. The pin spells the boolean
/// literals `Bool.true`/`Bool.false`; the prelude's bare `true`/`false` aliases are
/// definitionally the same, which is exactly what `is_def_eq` certifies.
fn pin_k2_ite_disjunctive() -> Expr {
    pi(
        bool_(), // c
        pi(
            nat(), // a
            pi(
                nat(), // b
                pi(
                    nat(), // v
                    iff(
                        eq1(
                            nat(),
                            v(0), // v
                            apps(
                                cl("ite", vec![l1()]),
                                [
                                    nat(),
                                    eq1(bool_(), v(3), cn("Bool.true")),
                                    apps(cn("instDecidableEqBool"), [v(3), cn("Bool.true")]),
                                    v(2), // a
                                    v(1), // b
                                ],
                            ),
                        ),
                        or(
                            and(eq1(bool_(), v(3), cn("Bool.true")), eq1(nat(), v(0), v(2))),
                            and(eq1(bool_(), v(3), cn("Bool.false")), eq1(nat(), v(0), v(1))),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// STRETCH — `ColCard.length_rangeList` (G1_column_cardinality.clean): the enumerated column
/// domain has exactly its declared cardinality:
///
/// ```text
/// (r : Nat) -> @Eq Nat (@List.length Nat (rangeList r)) r
/// ```
fn pin_length_range_list() -> Expr {
    pi(
        nat(),
        eq1(nat(), len0(nat(), app(cn("ColCard.rangeList"), v(0))), v(0)),
    )
}

/// STRETCH — `TupleCount.allTuples_length` (G1b_universe_count.clean): the enumerated state
/// universe has exactly the product cardinality:
///
/// ```text
/// (rs : List Nat) -> @Eq Nat (@List.length (List Nat) (allTuples rs)) (prod rs)
/// ```
fn pin_all_tuples_length() -> Expr {
    pi(
        list_nat(),
        eq1(
            nat(),
            apps(
                cl("List.length", vec![l0()]),
                [list_nat(), app(cn("TupleCount.allTuples"), v(0))],
            ),
            app(cn("TupleCount.prod"), v(0)),
        ),
    )
}

// ═══════════════════════════════════════════════════════════════════════════════════════════
// Harness. Elaborating the proof FILES (below) is the ONLY place the parser/elaborator run:
// the registered types they produce are the objects UNDER TEST. No pin is built from them.
// ═══════════════════════════════════════════════════════════════════════════════════════════

fn proofs_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("proofs/clean")
}

/// Elaborate one `.clean` proof file into a fresh prelude environment (the exact
/// `clean check` pipeline; same load pattern as `clean_soundness_proofs.rs`).
fn load_env(file: &str) -> Environment {
    let path = proofs_dir().join(file);
    let src =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut env = Environment::with_prelude();
    let mut fc = FileContext::new();
    let decls = parse_file(&src).unwrap_or_else(|e| panic!("{file}: parse error: {e:?}"));
    for d in &decls {
        let p = preprocess_decl_with_context(d, &mut fc);
        elaborate_decl_and_register(&mut env, &p)
            .unwrap_or_else(|e| panic!("{file}: elaboration failed: {e}"));
    }
    env
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    /// The "never a false safe" core — the test HARD-FAILS if any of these is unpinned.
    Flagship,
    /// Additional pinned statements (as many as feasible).
    Stretch,
    /// Supporting shape pins: the `Reach` inductive (type + constructors) per declaring file,
    /// and `SetMaskSound.mem`'s type. Not counted as theorem statements.
    Aux,
}

struct PinSpec {
    file: &'static str,
    name: &'static str,
    kind: Kind,
    build: fn() -> Expr,
}

const PINS: &[PinSpec] = &[
    // ── flagships ────────────────────────────────────────────────────────────────────────
    PinSpec {
        file: "tB_reachable_mem_R.clean",
        name: "reach_least",
        kind: Kind::Flagship,
        build: pin_reach_least,
    },
    PinSpec {
        file: "S1_pack_injective.clean",
        name: "PackInj.pack_injective",
        kind: Kind::Flagship,
        build: pin_pack_injective,
    },
    PinSpec {
        file: "S1b_mixed_radix_injective.clean",
        name: "MixedRadixInj.mixed_radix_injective",
        kind: Kind::Flagship,
        build: pin_mixed_radix_injective,
    },
    PinSpec {
        file: "M1_setmask_soundness.clean",
        name: "SetMaskSound.mask_injective",
        kind: Kind::Flagship,
        build: pin_mask_injective,
    },
    PinSpec {
        file: "d4_no_infinite_descent.clean",
        name: "d4_no_infinite_descent",
        kind: Kind::Flagship,
        build: pin_d4_no_infinite_descent,
    },
    PinSpec {
        file: "d3_step_simulation.clean",
        name: "d3_step_simulation",
        kind: Kind::Flagship,
        build: pin_d3_step_simulation,
    },
    // ── stretch ──────────────────────────────────────────────────────────────────────────
    PinSpec {
        file: "d3b_refinement_safety_transfer.clean",
        name: "refinement_safety_transfer",
        kind: Kind::Stretch,
        build: pin_refinement_safety_transfer,
    },
    PinSpec {
        file: "d3c_refinement_transitivity.clean",
        name: "refinement_transitivity",
        kind: Kind::Stretch,
        build: pin_refinement_transitivity,
    },
    PinSpec {
        file: "d4b_lex_liveness.clean",
        name: "LexLive.no_infinite_lex_descent",
        kind: Kind::Stretch,
        build: pin_no_infinite_lex_descent,
    },
    PinSpec {
        file: "L1b_mixed_radix_coverage.clean",
        name: "L1bMixed.mixed_radix_coverage",
        kind: Kind::Stretch,
        build: pin_mixed_radix_coverage,
    },
    PinSpec {
        file: "L1_domain_covers.clean",
        name: "L1Cover.baseValue_lt_pow",
        kind: Kind::Stretch,
        build: pin_base_value_lt_pow,
    },
    PinSpec {
        file: "R1_general_membership.clean",
        name: "R1_general_membership",
        kind: Kind::Stretch,
        build: pin_r1_general_membership,
    },
    PinSpec {
        file: "K2_ite_disjunctive.clean",
        name: "K2_ite_disjunctive",
        kind: Kind::Stretch,
        build: pin_k2_ite_disjunctive,
    },
    PinSpec {
        file: "G1_column_cardinality.clean",
        name: "ColCard.length_rangeList",
        kind: Kind::Stretch,
        build: pin_length_range_list,
    },
    PinSpec {
        file: "G1b_universe_count.clean",
        name: "TupleCount.allTuples_length",
        kind: Kind::Stretch,
        build: pin_all_tuples_length,
    },
    // ── aux: the Reach inductive's shape, per file that declares it ──────────────────────
    PinSpec {
        file: "tB_reachable_mem_R.clean",
        name: "Reach",
        kind: Kind::Aux,
        build: pin_reach_type,
    },
    PinSpec {
        file: "tB_reachable_mem_R.clean",
        name: "Reach.base",
        kind: Kind::Aux,
        build: pin_reach_base,
    },
    PinSpec {
        file: "tB_reachable_mem_R.clean",
        name: "Reach.step",
        kind: Kind::Aux,
        build: pin_reach_step,
    },
    PinSpec {
        file: "d3_step_simulation.clean",
        name: "Reach",
        kind: Kind::Aux,
        build: pin_reach_type,
    },
    PinSpec {
        file: "d3_step_simulation.clean",
        name: "Reach.base",
        kind: Kind::Aux,
        build: pin_reach_base,
    },
    PinSpec {
        file: "d3_step_simulation.clean",
        name: "Reach.step",
        kind: Kind::Aux,
        build: pin_reach_step,
    },
    PinSpec {
        file: "d3b_refinement_safety_transfer.clean",
        name: "Reach",
        kind: Kind::Aux,
        build: pin_reach_type,
    },
    PinSpec {
        file: "d3b_refinement_safety_transfer.clean",
        name: "Reach.base",
        kind: Kind::Aux,
        build: pin_reach_base,
    },
    PinSpec {
        file: "d3b_refinement_safety_transfer.clean",
        name: "Reach.step",
        kind: Kind::Aux,
        build: pin_reach_step,
    },
    PinSpec {
        file: "d3c_refinement_transitivity.clean",
        name: "Reach",
        kind: Kind::Aux,
        build: pin_reach_type,
    },
    PinSpec {
        file: "d3c_refinement_transitivity.clean",
        name: "Reach.base",
        kind: Kind::Aux,
        build: pin_reach_base,
    },
    PinSpec {
        file: "d3c_refinement_transitivity.clean",
        name: "Reach.step",
        kind: Kind::Aux,
        build: pin_reach_step,
    },
    // ── aux: SetMaskSound.mem's TYPE (its VALUE is pinned in value_pin_setmask_mem_body) ─
    PinSpec {
        file: "M1_setmask_soundness.clean",
        name: "SetMaskSound.mem",
        kind: Kind::Aux,
        build: pin_mem_type,
    },
];

/// Elaborate each distinct proof file exactly once.
fn load_all_envs() -> BTreeMap<&'static str, Environment> {
    let mut envs: BTreeMap<&'static str, Environment> = BTreeMap::new();
    for spec in PINS {
        envs.entry(spec.file).or_insert_with(|| load_env(spec.file));
    }
    envs
}

/// THE PIN CHECK: every registered statement must be definitionally equal to its hand-built,
/// elaborator-free pin. A failure prints BOTH exprs (pin then registered) for diagnosis.
#[test]
fn statement_pins_hold() {
    let envs = load_all_envs();
    let mut failures: Vec<String> = Vec::new();
    let mut pinned_statements = 0usize;
    let mut pinned_aux = 0usize;
    let mut flagships_unpinned: Vec<&str> = Vec::new();

    for spec in PINS {
        let env = &envs[spec.file];
        let Some(c) = env.get_const(&Name::from_string(spec.name)) else {
            failures.push(format!(
                "{}: constant `{}` did not register",
                spec.file, spec.name
            ));
            if spec.kind == Kind::Flagship {
                flagships_unpinned.push(spec.name);
            }
            continue;
        };
        // Statements here are all level-monomorphic; a level-parametric registration would
        // make the concrete-level pin silently vacuous, so reject it loudly.
        if !c.level_params.is_empty() {
            failures.push(format!(
                "{}: `{}` registered with unexpected level params {:?}",
                spec.file, spec.name, c.level_params
            ));
            if spec.kind == Kind::Flagship {
                flagships_unpinned.push(spec.name);
            }
            continue;
        }
        let pin = (spec.build)();
        if TypeChecker::new(env).is_def_eq(&pin, &c.type_) {
            match spec.kind {
                Kind::Aux => {
                    pinned_aux += 1;
                    println!("PINNED (aux): {} [{}]", spec.name, spec.file);
                }
                _ => {
                    pinned_statements += 1;
                    println!("PINNED: {} [{}]", spec.name, spec.file);
                }
            }
        } else {
            if spec.kind == Kind::Flagship {
                flagships_unpinned.push(spec.name);
            }
            eprintln!("PIN MISMATCH: {} [{}]", spec.name, spec.file);
            eprintln!("  PIN (hand-built):  {:?}", pin);
            eprintln!("  REGISTERED type:   {:?}", c.type_);
            failures.push(format!(
                "{}: `{}` registered type is NOT def-eq to its hand-built pin",
                spec.file, spec.name
            ));
        }
    }

    println!(
        "{pinned_statements} statements pinned (raw-Expr, elaborator-free); {} flagships \
         unpinned: {flagships_unpinned:?}",
        flagships_unpinned.len()
    );
    println!(
        "plus {pinned_aux} auxiliary shape pins (Reach type+constructors per declaring file; \
         SetMaskSound.mem type)"
    );

    assert!(
        failures.is_empty(),
        "{} statement pin(s) FAILED:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
    assert!(
        flagships_unpinned.is_empty(),
        "flagship statement(s) unpinned: {flagships_unpinned:?}"
    );
}

/// VALUE PIN — `SetMaskSound.mem`'s defining body must be definitionally
/// `fun (m i : Nat) => Nat.testBit m i`. With the mem body pinned, `mask_injective`'s pinned
/// statement bottoms out entirely in prelude constants.
#[test]
fn value_pin_setmask_mem_body() {
    let env = load_env("M1_setmask_soundness.clean");
    let c = env
        .get_const(&Name::from_string("SetMaskSound.mem"))
        .expect("SetMaskSound.mem registered");
    let value = c
        .value
        .as_ref()
        .expect("SetMaskSound.mem has a defining value");
    let pin = pin_mem_value();
    assert!(
        TypeChecker::new(&env).is_def_eq(&pin, value),
        "SetMaskSound.mem body is NOT def-eq to `fun (m i : Nat) => Nat.testBit m i`\n  \
         PIN:        {pin:?}\n  REGISTERED: {value:?}"
    );
    println!("PINNED (value): SetMaskSound.mem [M1_setmask_soundness.clean]");
}

// ═══════════════════════════════════════════════════════════════════════════════════════════
// NEGATIVE CONTROLS — deliberately WRONG pins must NOT be def-eq, proving the comparison is
// load-bearing (a rubber-stamp is_def_eq would green every mistranslation).
// ═══════════════════════════════════════════════════════════════════════════════════════════

/// A `reach_least` pin whose CONCLUSION is `Init s` instead of `R s` — the exact shape of a
/// statement-translation bug (right telescope, wrong proposition proved).
fn wrong_pin_reach_least_concl_init() -> Expr {
    pi(
        type0(),
        pi(
            arr(v(0), prop()),
            pi(
                arr(v(1), arr(v(2), prop())),
                pi(
                    arr(v(2), prop()),
                    pi(
                        pi(v(3), arr(app(v(3), v(0)), app(v(2), v(1)))),
                        pi(
                            pi(
                                v(4),
                                pi(
                                    v(5),
                                    arr(
                                        app(v(3), v(1)),
                                        arr(apps(v(5), [v(2), v(1)]), app(v(5), v(2))),
                                    ),
                                ),
                            ),
                            pi(
                                v(5),
                                arr(
                                    apps(cn("Reach"), [v(6), v(5), v(4), v(0)]),
                                    // WRONG: `Init s` (Init@6) instead of `R s` (R@4)
                                    app(v(6), v(1)),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// A `reach_least` pin with `hstep`'s hypotheses SWAPPED (`Next s t -> R s -> R t` instead of
/// `R s -> Next s t -> R t`) — a binder-order mistranslation.
fn wrong_pin_reach_least_swapped_hstep() -> Expr {
    pi(
        type0(),
        pi(
            arr(v(0), prop()),
            pi(
                arr(v(1), arr(v(2), prop())),
                pi(
                    arr(v(2), prop()),
                    pi(
                        pi(v(3), arr(app(v(3), v(0)), app(v(2), v(1)))),
                        pi(
                            // WRONG hstep: (s t : State) -> Next s t -> R s -> R t
                            pi(
                                v(4),
                                pi(
                                    v(5),
                                    arr(
                                        // context here: t@0, s@1, hinit@2, R@3, Next@4, Init@5
                                        apps(v(4), [v(1), v(0)]), // Next s t (swapped in)
                                        arr(app(v(4), v(2)), app(v(5), v(2))), // R s -> R t
                                    ),
                                ),
                            ),
                            pi(
                                v(5),
                                arr(apps(cn("Reach"), [v(6), v(5), v(4), v(0)]), app(v(4), v(1))),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// NEGATIVE CONTROL 1: the wrong-conclusion pin must NOT be def-eq to `reach_least`'s
/// registered type.
#[test]
fn negative_control_wrong_conclusion_is_rejected() {
    let env = load_env("tB_reachable_mem_R.clean");
    let c = env
        .get_const(&Name::from_string("reach_least"))
        .expect("reach_least registered");
    assert!(
        !TypeChecker::new(&env).is_def_eq(&wrong_pin_reach_least_concl_init(), &c.type_),
        "a pin concluding `Init s` instead of `R s` MUST NOT be def-eq to reach_least — if it \
         is, the pin comparison is not actually checking statements"
    );
}

/// NEGATIVE CONTROL 2: the swapped-hypothesis pin must NOT be def-eq to `reach_least`'s
/// registered type (binder order is part of the statement).
#[test]
fn negative_control_swapped_binders_is_rejected() {
    let env = load_env("tB_reachable_mem_R.clean");
    let c = env
        .get_const(&Name::from_string("reach_least"))
        .expect("reach_least registered");
    assert!(
        !TypeChecker::new(&env).is_def_eq(&wrong_pin_reach_least_swapped_hstep(), &c.type_),
        "a pin with hstep's hypotheses swapped MUST NOT be def-eq to reach_least"
    );
}

/// NEGATIVE CONTROL 3: a CORRECT pin compared against a DIFFERENT theorem's registered type
/// must fail — `mask_injective`'s pin vs `SetMaskSound.union_comm` (same file, same env).
#[test]
fn negative_control_cross_theorem_is_rejected() {
    let env = load_env("M1_setmask_soundness.clean");
    let other = env
        .get_const(&Name::from_string("SetMaskSound.union_comm"))
        .expect("SetMaskSound.union_comm registered");
    assert!(
        !TypeChecker::new(&env).is_def_eq(&pin_mask_injective(), &other.type_),
        "mask_injective's pin MUST NOT be def-eq to union_comm's type — distinct theorems must \
         not satisfy each other's pins"
    );
}
